/* Generated by re2c 1.0.2 */
#line 1 "src/lib/amipack_parse.re"
/**
 * amiws -- Library with functions for read/create AMI packets
 * Copyright (C) 2016, Stas Kobzar <staskobzar@modulis.ca>
 *
 * This file is part of amiws.
 *
 * amiws is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * amiws is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with amiws.  If not, see <http://www.gnu.org/licenses/>.
 */

/**
 * @file amipack_parse.c
 * @brief AMI (Asterisk Management Interface) packet parser.
 *
 * @author Stas Kobzar <stas.kobzar@modulis.ca>
 */

#include <stdio.h>
#include <string.h>
#include "amipack.h"

/**
 * Commands to run when known header parsed.
 * @param name    Header type
 */
#define SET_HEADER(name)  len = cur - tok; \
                          hdr_name = strdup(name); \
                          goto yyc_key;

/**
 * Commands to run on Command AMI response header.
 * @param offset  Header name offset
 * @param name    Header type
 */
#define CMD_HEADER(offset, name) len = cur - tok - offset; tok += offset; \
                          while(*tok == ' ') { tok++; len--; } \
                          len -= 2; \
                          char *val = strndup(tok, len); \
                          amipack_append (pack, strdup(name), strlen(name), val, len); \
                          tok = cur; goto yyc_command;

// introducing types:re2c for AMI packet
/*! re2c parcing conditions. */
enum yycond_pack {
  yyckey,
  yycvalue,
  yyccommand,
  yycqueue
};

AMIPacket *amiparse_pack (const char *pack_str)
{
  AMIPacket *pack = amipack_init ();
  const char *marker = pack_str;
  const char *cur    = marker;
  const char *ctxmarker;
  int c = yyckey;
  int len = 0;

  char *yyt1;
char *yyt2;
char *yyt3;


  const char *tok = marker;
  char *hdr_name;
  // stags
  char *tq1, *tq2, *tq3, *tq4, *tq5, *tq6;


#line 84 "src/lib/amipack_parse.c"
{
	unsigned char yych;
	unsigned int yyaccept = 0;
	switch (c) {
	case yyckey: goto yyc_key;
	case yycqueue: goto yyc_queue;
	case yycvalue: goto yyc_value;
	case yyccommand: goto yyc_command;
	}
/* *********************************** */
yyc_key:
	yych = *cur;
	switch (yych) {
	case '\r':
		yyt1 = cur;
		goto yy6;
	case ' ':	goto yy7;
	case ':':
		yyt1 = cur;
		goto yy9;
	case 'A':
	case 'a':
		yyt1 = cur;
		goto yy11;
	case 'E':
	case 'e':
		yyt1 = cur;
		goto yy12;
	case 'R':
	case 'r':
		yyt1 = cur;
		goto yy13;
	default:
		yyt1 = cur;
		goto yy3;
	}
yy3:
	yyaccept = 0;
	yych = *(marker = ++cur);
yy4:
	switch (yych) {
	case ' ':	goto yy14;
	case ':':	goto yy16;
	default:	goto yy3;
	}
yy5:
#line 149 "src/lib/amipack_parse.re"
	{
              len = cur - tok;
              hdr_name = strndup(tok, len);
              goto yyc_key;
            }
#line 137 "src/lib/amipack_parse.c"
yy6:
	yyaccept = 0;
	yych = *(marker = ++cur);
	switch (yych) {
	case '\n':	goto yy18;
	default:	goto yy4;
	}
yy7:
	++cur;
#line 103 "src/lib/amipack_parse.re"
	{
              printf("====== UNKNOWN ERROR =====\n");
              if (hdr_name) free (hdr_name);
              amipack_destroy (pack);
              return NULL;
            }
#line 154 "src/lib/amipack_parse.c"
yy9:
	yyaccept = 1;
	yych = *(marker = ++cur);
	switch (yych) {
	case '\r':	goto yy19;
	case ' ':	goto yy20;
	default:	goto yy16;
	}
yy10:
#line 118 "src/lib/amipack_parse.re"
	{ tok = cur; goto yyc_value; }
#line 166 "src/lib/amipack_parse.c"
yy11:
	yyaccept = 0;
	yych = *(marker = ++cur);
	switch (yych) {
	case 'C':
	case 'c':	goto yy21;
	default:	goto yy4;
	}
yy12:
	yyaccept = 0;
	yych = *(marker = ++cur);
	switch (yych) {
	case 'V':
	case 'v':	goto yy22;
	default:	goto yy4;
	}
yy13:
	yyaccept = 0;
	yych = *(marker = ++cur);
	switch (yych) {
	case 'E':
	case 'e':	goto yy23;
	default:	goto yy4;
	}
yy14:
	yych = *++cur;
	switch (yych) {
	case 'h':	goto yy24;
	default:	goto yy15;
	}
yy15:
	cur = marker;
	switch (yyaccept) {
	case 0: 	goto yy5;
	case 1: 	goto yy10;
	case 2: 	goto yy35;
	case 3: 	goto yy38;
	case 4: 	goto yy45;
	case 5: 	goto yy50;
	case 6: 	goto yy55;
	case 7: 	goto yy62;
	default:	goto yy94;
	}
yy16:
	yych = *++cur;
yy17:
	switch (yych) {
	case ' ':	goto yy14;
	default:	goto yy16;
	}
yy18:
	yyaccept = 0;
	yych = *(marker = ++cur);
	switch (yych) {
	case '\r':	goto yy25;
	default:	goto yy4;
	}
yy19:
	yych = *++cur;
	switch (yych) {
	case '\n':	goto yy26;
	default:	goto yy17;
	}
yy20:
	yyaccept = 1;
	yych = *(marker = ++cur);
	switch (yych) {
	case 'h':	goto yy24;
	default:	goto yy29;
	}
yy21:
	yyaccept = 0;
	yych = *(marker = ++cur);
	switch (yych) {
	case 'T':
	case 't':	goto yy30;
	default:	goto yy4;
	}
yy22:
	yyaccept = 0;
	yych = *(marker = ++cur);
	switch (yych) {
	case 'E':
	case 'e':	goto yy31;
	default:	goto yy4;
	}
yy23:
	yyaccept = 0;
	yych = *(marker = ++cur);
	switch (yych) {
	case 'S':
	case 's':	goto yy32;
	default:	goto yy4;
	}
yy24:
	yych = *++cur;
	switch (yych) {
	case 'a':	goto yy33;
	default:	goto yy15;
	}
yy25:
	yyaccept = 0;
	yych = *(marker = ++cur);
	switch (yych) {
	case '\n':	goto yy34;
	default:	goto yy4;
	}
yy26:
	yych = *++cur;
	switch (yych) {
	case '\r':	goto yy36;
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy37;
	default:	goto yy17;
	}
yy27:
	yych = *++cur;
	switch (yych) {
	case '\n':	goto yy39;
	default:	goto yy15;
	}
yy28:
	yyaccept = 1;
	yych = *(marker = ++cur);
yy29:
	switch (yych) {
	case '\r':	goto yy27;
	case ' ':	goto yy28;
	default:	goto yy10;
	}
yy30:
	yyaccept = 0;
	yych = *(marker = ++cur);
	switch (yych) {
	case 'I':
	case 'i':	goto yy40;
	default:	goto yy4;
	}
yy31:
	yyaccept = 0;
	yych = *(marker = ++cur);
	switch (yych) {
	case 'N':
	case 'n':	goto yy41;
	default:	goto yy4;
	}
yy32:
	yyaccept = 0;
	yych = *(marker = ++cur);
	switch (yych) {
	case 'P':
	case 'p':	goto yy42;
	default:	goto yy4;
	}
yy33:
	yych = *++cur;
	switch (yych) {
	case 's':	goto yy43;
	default:	goto yy15;
	}
yy34:
	yyaccept = 2;
	yych = *(marker = ++cur);
	goto yy4;
yy35:
#line 109 "src/lib/amipack_parse.re"
	{ goto done; }
#line 384 "src/lib/amipack_parse.c"
yy36:
	yych = *++cur;
	switch (yych) {
	case '\n':	goto yy44;
	default:	goto yy17;
	}
yy37:
	yyaccept = 3;
	yych = *(marker = ++cur);
	goto yy17;
yy38:
	cur -= 1;
#line 119 "src/lib/amipack_parse.re"
	{
              tok = cur;
              amipack_append(pack, hdr_name, strlen(hdr_name), strdup(""), 0);
              goto yyc_key;
            }
#line 403 "src/lib/amipack_parse.c"
yy39:
	yych = *++cur;
	switch (yych) {
	case '\r':	goto yy46;
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy47;
	default:	goto yy15;
	}
yy40:
	yyaccept = 0;
	yych = *(marker = ++cur);
	switch (yych) {
	case 'O':
	case 'o':	goto yy48;
	default:	goto yy4;
	}
yy41:
	yyaccept = 0;
	yych = *(marker = ++cur);
	switch (yych) {
	case 'T':
	case 't':	goto yy49;
	default:	goto yy4;
	}
yy42:
	yyaccept = 0;
	yych = *(marker = ++cur);
	switch (yych) {
	case 'O':
	case 'o':	goto yy51;
	default:	goto yy4;
	}
yy43:
	yych = *++cur;
	switch (yych) {
	case ' ':	goto yy52;
	default:	goto yy15;
	}
yy44:
	yyaccept = 4;
	yych = *(marker = ++cur);
	goto yy17;
yy45:
#line 124 "src/lib/amipack_parse.re"
	{
              tok = cur;
              amipack_append(pack, hdr_name, strlen(hdr_name), strdup(""), 0);
              goto done;
            }
#line 503 "src/lib/amipack_parse.c"
yy46:
	yych = *++cur;
	switch (yych) {
	case '\n':	goto yy53;
	default:	goto yy15;
	}
yy47:
	++cur;
	goto yy38;
yy48:
	yyaccept = 0;
	yych = *(marker = ++cur);
	switch (yych) {
	case 'N':
	case 'n':	goto yy54;
	default:	goto yy4;
	}
yy49:
	yyaccept = 5;
	yych = *(marker = ++cur);
	goto yy4;
yy50:
#line 144 "src/lib/amipack_parse.re"
	{
              amipack_type (pack, AMI_EVENT);
              SET_HEADER("Event");
            }
#line 531 "src/lib/amipack_parse.c"
yy51:
	yyaccept = 0;
	yych = *(marker = ++cur);
	switch (yych) {
	case 'N':
	case 'n':	goto yy56;
	default:	goto yy4;
	}
yy52:
	yych = *++cur;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
		yyt2 = cur;
		goto yy57;
	default:	goto yy15;
	}
yy53:
	++cur;
	goto yy45;
yy54:
	yyaccept = 6;
	yych = *(marker = ++cur);
	goto yy4;
yy55:
#line 140 "src/lib/amipack_parse.re"
	{
              amipack_type (pack, AMI_ACTION);
              SET_HEADER("Action");
            }
#line 570 "src/lib/amipack_parse.c"
yy56:
	yyaccept = 0;
	yych = *(marker = ++cur);
	switch (yych) {
	case 'S':
	case 's':	goto yy59;
	default:	goto yy4;
	}
yy57:
	yych = *++cur;
	switch (yych) {
	case ' ':	goto yy60;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy57;
	default:	goto yy15;
	}
yy59:
	yyaccept = 0;
	yych = *(marker = ++cur);
	switch (yych) {
	case 'E':
	case 'e':	goto yy61;
	default:	goto yy4;
	}
yy60:
	yych = *++cur;
	switch (yych) {
	case 'c':	goto yy63;
	default:	goto yy15;
	}
yy61:
	yyaccept = 7;
	yych = *(marker = ++cur);
	switch (yych) {
	case ':':	goto yy64;
	default:	goto yy4;
	}
yy62:
#line 136 "src/lib/amipack_parse.re"
	{
              amipack_type (pack, AMI_RESPONSE);
              SET_HEADER("Response");
            }
#line 622 "src/lib/amipack_parse.c"
yy63:
	yych = *++cur;
	switch (yych) {
	case 'a':	goto yy65;
	default:	goto yy15;
	}
yy64:
	yych = *++cur;
	switch (yych) {
	case ' ':	goto yy66;
	case 'F':
	case 'f':	goto yy67;
	default:	goto yy16;
	}
yy65:
	yych = *++cur;
	switch (yych) {
	case 'l':	goto yy68;
	default:	goto yy15;
	}
yy66:
	yych = *++cur;
	switch (yych) {
	case 'h':	goto yy24;
	default:	goto yy70;
	}
yy67:
	yych = *++cur;
	switch (yych) {
	case 'O':
	case 'o':	goto yy72;
	default:	goto yy17;
	}
yy68:
	yych = *++cur;
	switch (yych) {
	case 'l':	goto yy73;
	default:	goto yy15;
	}
yy69:
	yych = *++cur;
yy70:
	switch (yych) {
	case ' ':	goto yy69;
	case 'F':
	case 'f':	goto yy71;
	default:	goto yy15;
	}
yy71:
	yych = *++cur;
	switch (yych) {
	case 'O':
	case 'o':	goto yy74;
	default:	goto yy15;
	}
yy72:
	yych = *++cur;
	switch (yych) {
	case 'L':
	case 'l':	goto yy75;
	default:	goto yy17;
	}
yy73:
	yych = *++cur;
	switch (yych) {
	case 's':	goto yy76;
	default:	goto yy15;
	}
yy74:
	yych = *++cur;
	switch (yych) {
	case 'L':
	case 'l':	goto yy77;
	default:	goto yy15;
	}
yy75:
	yych = *++cur;
	switch (yych) {
	case 'L':
	case 'l':	goto yy78;
	default:	goto yy17;
	}
yy76:
	yych = *++cur;
	switch (yych) {
	case ' ':	goto yy79;
	default:	goto yy15;
	}
yy77:
	yych = *++cur;
	switch (yych) {
	case 'L':
	case 'l':	goto yy80;
	default:	goto yy15;
	}
yy78:
	yych = *++cur;
	switch (yych) {
	case 'O':
	case 'o':	goto yy81;
	default:	goto yy17;
	}
yy79:
	yych = *++cur;
	switch (yych) {
	case '(':	goto yy82;
	default:	goto yy15;
	}
yy80:
	yych = *++cur;
	switch (yych) {
	case 'O':
	case 'o':	goto yy83;
	default:	goto yy15;
	}
yy81:
	yych = *++cur;
	switch (yych) {
	case 'W':
	case 'w':	goto yy84;
	default:	goto yy17;
	}
yy82:
	yych = *++cur;
	switch (yych) {
	case 'm':	goto yy85;
	default:	goto yy15;
	}
yy83:
	yych = *++cur;
	switch (yych) {
	case 'W':
	case 'w':	goto yy86;
	default:	goto yy15;
	}
yy84:
	yych = *++cur;
	switch (yych) {
	case 'S':
	case 's':	goto yy87;
	default:	goto yy17;
	}
yy85:
	yych = *++cur;
	switch (yych) {
	case 'a':	goto yy88;
	default:	goto yy15;
	}
yy86:
	yych = *++cur;
	switch (yych) {
	case 'S':
	case 's':	goto yy89;
	default:	goto yy15;
	}
yy87:
	yych = *++cur;
	switch (yych) {
	case '\r':	goto yy90;
	default:	goto yy17;
	}
yy88:
	yych = *++cur;
	switch (yych) {
	case 'x':	goto yy91;
	default:	goto yy15;
	}
yy89:
	yych = *++cur;
	switch (yych) {
	case '\r':	goto yy92;
	default:	goto yy15;
	}
yy90:
	yych = *++cur;
	switch (yych) {
	case '\n':	goto yy93;
	default:	goto yy17;
	}
yy91:
	yych = *++cur;
	switch (yych) {
	case ' ':	goto yy95;
	default:	goto yy15;
	}
yy92:
	yych = *++cur;
	switch (yych) {
	case '\n':	goto yy96;
	default:	goto yy15;
	}
yy93:
	yyaccept = 8;
	yych = *(marker = ++cur);
	goto yy17;
yy94:
#line 129 "src/lib/amipack_parse.re"
	{
              len = cur - tok;
              tok = cur;
              amipack_type (pack, AMI_RESPONSE);
              amipack_append(pack, strdup("Response"), 8, strdup("Follows"), 7);
              goto yyc_command;
            }
#line 827 "src/lib/amipack_parse.c"
yy95:
	yych = *++cur;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':
		yyt3 = cur;
		goto yy97;
	default:	goto yy15;
	}
yy96:
	++cur;
	goto yy94;
yy97:
	yych = *++cur;
	switch (yych) {
	case ')':	goto yy99;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy97;
	default:	goto yy15;
	}
yy99:
	yych = *++cur;
	switch (yych) {
	case ' ':	goto yy100;
	default:	goto yy15;
	}
yy100:
	++cur;
	tq1 = yyt1;
	tq3 = yyt2;
	tq5 = yyt3;
	tq2 = yyt2 - 5;
	tq4 = yyt3 - 12;
	tq6 = cur - 2;
#line 111 "src/lib/amipack_parse.re"
	{
              printf("Queue name: %.*s\n", (int)(tq2 - tq1), tq1);
              printf("Queue calls: %.*s\n", (int)(tq4 - tq3), tq3);
              printf("Queue max calls: %.*s\n", (int)(tq6 - tq5), tq5);
              amipack_type (pack, AMI_QUEUES);
              goto yyc_queue;
            }
#line 938 "src/lib/amipack_parse.c"
/* *********************************** */
yyc_queue:
	yych = *cur;
	switch (yych) {
	case '\r':	goto yy106;
	case 'S':	goto yy107;
	case 'W':	goto yy108;
	case 'i':	goto yy109;
	default:	goto yy104;
	}
yy104:
	++cur;
yy105:
#line 103 "src/lib/amipack_parse.re"
	{
              printf("====== UNKNOWN ERROR =====\n");
              if (hdr_name) free (hdr_name);
              amipack_destroy (pack);
              return NULL;
            }
#line 959 "src/lib/amipack_parse.c"
yy106:
	yych = *(marker = ++cur);
	switch (yych) {
	case '\n':	goto yy110;
	default:	goto yy105;
	}
yy107:
	yych = *(marker = ++cur);
	switch (yych) {
	case 'L':	goto yy112;
	default:	goto yy105;
	}
yy108:
	yych = *(marker = ++cur);
	switch (yych) {
	case ':':	goto yy113;
	default:	goto yy105;
	}
yy109:
	yych = *(marker = ++cur);
	switch (yych) {
	case 'n':	goto yy114;
	default:	goto yy105;
	}
yy110:
	yych = *++cur;
	switch (yych) {
	case '\r':	goto yy115;
	default:	goto yy111;
	}
yy111:
	cur = marker;
	goto yy105;
yy112:
	yych = *++cur;
	switch (yych) {
	case ':':	goto yy116;
	default:	goto yy111;
	}
yy113:
	yych = *++cur;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
		yyt1 = cur;
		goto yy117;
	default:	goto yy111;
	}
yy114:
	yych = *++cur;
	switch (yych) {
	case ' ':	goto yy119;
	default:	goto yy111;
	}
yy115:
	yych = *++cur;
	switch (yych) {
	case '\n':	goto yy120;
	default:	goto yy111;
	}
yy116:
	yych = *++cur;
	switch (yych) {
	case '.':
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
		yyt1 = cur;
		goto yy122;
	default:	goto yy111;
	}
yy117:
	yych = *++cur;
	switch (yych) {
	case ',':	goto yy124;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy117;
	default:	goto yy111;
	}
yy119:
	yych = *++cur;
	switch (yych) {
	case '\'':	goto yy125;
	default:	goto yy111;
	}
yy120:
	++cur;
#line 109 "src/lib/amipack_parse.re"
	{ goto done; }
#line 1072 "src/lib/amipack_parse.c"
yy122:
	yych = *++cur;
	switch (yych) {
	case '%':	goto yy126;
	case '.':
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy122;
	default:	goto yy111;
	}
yy124:
	yych = *++cur;
	switch (yych) {
	case ' ':	goto yy127;
	default:	goto yy111;
	}
yy125:
	yych = *++cur;
	switch (yych) {
	case '\'':	goto yy111;
	default:
		yyt1 = cur;
		goto yy128;
	}
yy126:
	yych = *++cur;
	switch (yych) {
	case ' ':	goto yy130;
	default:	goto yy111;
	}
yy127:
	yych = *++cur;
	switch (yych) {
	case 'C':	goto yy131;
	default:	goto yy111;
	}
yy128:
	yych = *++cur;
	switch (yych) {
	case '\'':	goto yy132;
	default:	goto yy128;
	}
yy130:
	yych = *++cur;
	switch (yych) {
	case 'w':	goto yy133;
	default:	goto yy111;
	}
yy131:
	yych = *++cur;
	switch (yych) {
	case ':':	goto yy134;
	default:	goto yy111;
	}
yy132:
	yych = *++cur;
	switch (yych) {
	case ' ':	goto yy135;
	default:	goto yy111;
	}
yy133:
	yych = *++cur;
	switch (yych) {
	case 'i':	goto yy136;
	default:	goto yy111;
	}
yy134:
	yych = *++cur;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
		yyt2 = cur;
		goto yy137;
	default:	goto yy111;
	}
yy135:
	yych = *++cur;
	switch (yych) {
	case 's':	goto yy139;
	default:	goto yy111;
	}
yy136:
	yych = *++cur;
	switch (yych) {
	case 't':	goto yy140;
	default:	goto yy111;
	}
yy137:
	yych = *++cur;
	switch (yych) {
	case ',':	goto yy141;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy137;
	default:	goto yy111;
	}
yy139:
	yych = *++cur;
	switch (yych) {
	case 't':	goto yy142;
	default:	goto yy111;
	}
yy140:
	yych = *++cur;
	switch (yych) {
	case 'h':	goto yy143;
	default:	goto yy111;
	}
yy141:
	yych = *++cur;
	switch (yych) {
	case ' ':	goto yy144;
	default:	goto yy111;
	}
yy142:
	yych = *++cur;
	switch (yych) {
	case 'r':	goto yy145;
	default:	goto yy111;
	}
yy143:
	yych = *++cur;
	switch (yych) {
	case 'i':	goto yy146;
	default:	goto yy111;
	}
yy144:
	yych = *++cur;
	switch (yych) {
	case 'A':	goto yy147;
	default:	goto yy111;
	}
yy145:
	yych = *++cur;
	switch (yych) {
	case 'a':	goto yy148;
	default:	goto yy111;
	}
yy146:
	yych = *++cur;
	switch (yych) {
	case 'n':	goto yy149;
	default:	goto yy111;
	}
yy147:
	yych = *++cur;
	switch (yych) {
	case ':':	goto yy150;
	default:	goto yy111;
	}
yy148:
	yych = *++cur;
	switch (yych) {
	case 't':	goto yy151;
	default:	goto yy111;
	}
yy149:
	yych = *++cur;
	switch (yych) {
	case ' ':	goto yy152;
	default:	goto yy111;
	}
yy150:
	yych = *++cur;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
		yyt3 = cur;
		goto yy153;
	default:	goto yy111;
	}
yy151:
	yych = *++cur;
	switch (yych) {
	case 'e':	goto yy155;
	default:	goto yy111;
	}
yy152:
	yych = *++cur;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
		yyt2 = cur;
		goto yy156;
	default:	goto yy111;
	}
yy153:
	yych = *++cur;
	switch (yych) {
	case ',':	goto yy158;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy153;
	default:	goto yy111;
	}
yy155:
	yych = *++cur;
	switch (yych) {
	case 'g':	goto yy159;
	default:	goto yy111;
	}
yy156:
	yych = *++cur;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy156;
	case 's':	goto yy160;
	default:	goto yy111;
	}
yy158:
	yych = *++cur;
	switch (yych) {
	case ' ':	goto yy162;
	default:	goto yy111;
	}
yy159:
	yych = *++cur;
	switch (yych) {
	case 'y':	goto yy164;
	default:	goto yy111;
	}
yy160:
	++cur;
	tq1 = yyt1;
	tq3 = yyt2;
	tq2 = yyt2 - 9;
	tq4 = cur - 1;
#line 187 "src/lib/amipack_parse.re"
	{
              printf("Queue service level: %.*s%%\n", (int)(tq2 - tq1), tq1);
              printf("Queue service level time period: %.*s\n", (int)(tq4 - tq3), tq3);
              goto yyc_queue;
          }
#line 1359 "src/lib/amipack_parse.c"
yy162:
	++cur;
	tq1 = yyt1;
	tq3 = yyt2;
	tq5 = yyt3;
	tq2 = yyt2 - 4;
	tq4 = yyt3 - 4;
	tq6 = cur - 2;
#line 181 "src/lib/amipack_parse.re"
	{
              printf("Queue wieght: %.*s\n", (int)(tq2 - tq1), tq1);
              printf("Queue calls answered: %.*s\n", (int)(tq4 - tq3), tq3);
              printf("Queue calls unanswered: %.*s\n", (int)(tq6 - tq5), tq5);
              goto yyc_queue;
          }
#line 1375 "src/lib/amipack_parse.c"
yy164:
	yych = *++cur;
	switch (yych) {
	case ' ':	goto yy165;
	default:	goto yy111;
	}
yy165:
	yych = *++cur;
	switch (yych) {
	case '(':	goto yy166;
	default:	goto yy111;
	}
yy166:
	yych = *++cur;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
		yyt2 = cur;
		goto yy167;
	default:	goto yy111;
	}
yy167:
	yych = *++cur;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy167;
	case 's':	goto yy169;
	default:	goto yy111;
	}
yy169:
	yych = *++cur;
	switch (yych) {
	case ' ':	goto yy170;
	default:	goto yy111;
	}
yy170:
	yych = *++cur;
	switch (yych) {
	case 'h':	goto yy171;
	default:	goto yy111;
	}
yy171:
	yych = *++cur;
	switch (yych) {
	case 'o':	goto yy172;
	default:	goto yy111;
	}
yy172:
	yych = *++cur;
	switch (yych) {
	case 'l':	goto yy173;
	default:	goto yy111;
	}
yy173:
	yych = *++cur;
	switch (yych) {
	case 'd':	goto yy174;
	default:	goto yy111;
	}
yy174:
	yych = *++cur;
	switch (yych) {
	case 't':	goto yy175;
	default:	goto yy111;
	}
yy175:
	yych = *++cur;
	switch (yych) {
	case 'i':	goto yy176;
	default:	goto yy111;
	}
yy176:
	yych = *++cur;
	switch (yych) {
	case 'm':	goto yy177;
	default:	goto yy111;
	}
yy177:
	yych = *++cur;
	switch (yych) {
	case 'e':	goto yy178;
	default:	goto yy111;
	}
yy178:
	yych = *++cur;
	switch (yych) {
	case ',':	goto yy179;
	default:	goto yy111;
	}
yy179:
	yych = *++cur;
	switch (yych) {
	case ' ':	goto yy180;
	default:	goto yy111;
	}
yy180:
	yych = *++cur;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
		yyt3 = cur;
		goto yy181;
	default:	goto yy111;
	}
yy181:
	yych = *++cur;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy181;
	case 's':	goto yy183;
	default:	goto yy111;
	}
yy183:
	yych = *++cur;
	switch (yych) {
	case ' ':	goto yy184;
	default:	goto yy111;
	}
yy184:
	yych = *++cur;
	switch (yych) {
	case 't':	goto yy185;
	default:	goto yy111;
	}
yy185:
	yych = *++cur;
	switch (yych) {
	case 'a':	goto yy186;
	default:	goto yy111;
	}
yy186:
	yych = *++cur;
	switch (yych) {
	case 'l':	goto yy187;
	default:	goto yy111;
	}
yy187:
	yych = *++cur;
	switch (yych) {
	case 'k':	goto yy188;
	default:	goto yy111;
	}
yy188:
	yych = *++cur;
	switch (yych) {
	case 't':	goto yy189;
	default:	goto yy111;
	}
yy189:
	yych = *++cur;
	switch (yych) {
	case 'i':	goto yy190;
	default:	goto yy111;
	}
yy190:
	yych = *++cur;
	switch (yych) {
	case 'm':	goto yy191;
	default:	goto yy111;
	}
yy191:
	yych = *++cur;
	switch (yych) {
	case 'e':	goto yy192;
	default:	goto yy111;
	}
yy192:
	yych = *++cur;
	switch (yych) {
	case ')':	goto yy193;
	default:	goto yy111;
	}
yy193:
	yych = *++cur;
	switch (yych) {
	case ',':	goto yy194;
	default:	goto yy111;
	}
yy194:
	yych = *++cur;
	switch (yych) {
	case ' ':	goto yy195;
	default:	goto yy111;
	}
yy195:
	++cur;
	tq1 = yyt1;
	tq3 = yyt2;
	tq5 = yyt3;
	tq2 = yyt2 - 12;
	tq4 = yyt3 - 12;
	tq6 = cur - 13;
#line 174 "src/lib/amipack_parse.re"
	{
              printf("====QUEUE=====\n");
              printf("Queue strategy: %.*s\n", (int)(tq2 - tq1), tq1);
              printf("Queue holdtime: %.*ss\n", (int)(tq4 - tq3), tq3);
              printf("Queue talktime: %.*ss\n", (int)(tq6 - tq5), tq5);
              goto yyc_queue;
          }
#line 1608 "src/lib/amipack_parse.c"
/* *********************************** */
yyc_value:
	yych = *cur;
	switch (yych) {
	case '\n':	goto yy202;
	case '\r':	goto yy204;
	default:	goto yy199;
	}
yy199:
	yych = *++cur;
	switch (yych) {
	case '\n':
	case '\r':	goto yy201;
	default:	goto yy199;
	}
yy201:
#line 156 "src/lib/amipack_parse.re"
	{
              len = cur - tok;
              char *val = strndup(tok, len);
              amipack_append(pack, hdr_name, strlen(hdr_name), val, len);
              goto yyc_value;
            }
#line 1632 "src/lib/amipack_parse.c"
yy202:
	++cur;
yy203:
#line 103 "src/lib/amipack_parse.re"
	{
              printf("====== UNKNOWN ERROR =====\n");
              if (hdr_name) free (hdr_name);
              amipack_destroy (pack);
              return NULL;
            }
#line 1643 "src/lib/amipack_parse.c"
yy204:
	yych = *(marker = ++cur);
	switch (yych) {
	case '\n':	goto yy205;
	default:	goto yy203;
	}
yy205:
	yych = *++cur;
	switch (yych) {
	case '\r':	goto yy207;
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy208;
	default:	goto yy206;
	}
yy206:
	cur = marker;
	goto yy203;
yy207:
	yych = *++cur;
	switch (yych) {
	case '\n':	goto yy210;
	default:	goto yy206;
	}
yy208:
	++cur;
	cur -= 1;
#line 155 "src/lib/amipack_parse.re"
	{ tok = cur; goto yyc_key; }
#line 1722 "src/lib/amipack_parse.c"
yy210:
	++cur;
#line 109 "src/lib/amipack_parse.re"
	{ goto done; }
#line 1727 "src/lib/amipack_parse.c"
/* *********************************** */
yyc_command:
	yych = *cur;
	switch (yych) {
	case '\n':	goto yy216;
	case '-':	goto yy218;
	case 'A':
	case 'a':	goto yy219;
	case 'M':
	case 'm':	goto yy220;
	case 'P':
	case 'p':	goto yy221;
	default:	goto yy214;
	}
yy214:
	yych = *++cur;
yy215:
	switch (yych) {
	case '\n':	goto yy216;
	default:	goto yy214;
	}
yy216:
	++cur;
yy217:
#line 167 "src/lib/amipack_parse.re"
	{ goto yyc_command; }
#line 1754 "src/lib/amipack_parse.c"
yy218:
	yych = *++cur;
	switch (yych) {
	case '-':	goto yy222;
	default:	goto yy215;
	}
yy219:
	yych = *++cur;
	switch (yych) {
	case 'C':
	case 'c':	goto yy223;
	default:	goto yy215;
	}
yy220:
	yych = *++cur;
	switch (yych) {
	case 'E':
	case 'e':	goto yy224;
	default:	goto yy215;
	}
yy221:
	yych = *++cur;
	switch (yych) {
	case 'R':
	case 'r':	goto yy225;
	default:	goto yy215;
	}
yy222:
	yych = *++cur;
	switch (yych) {
	case 'E':	goto yy226;
	default:	goto yy215;
	}
yy223:
	yych = *++cur;
	switch (yych) {
	case 'T':
	case 't':	goto yy227;
	default:	goto yy215;
	}
yy224:
	yych = *++cur;
	switch (yych) {
	case 'S':
	case 's':	goto yy228;
	default:	goto yy215;
	}
yy225:
	yych = *++cur;
	switch (yych) {
	case 'I':
	case 'i':	goto yy229;
	default:	goto yy215;
	}
yy226:
	yych = *++cur;
	switch (yych) {
	case 'N':	goto yy230;
	default:	goto yy215;
	}
yy227:
	yych = *++cur;
	switch (yych) {
	case 'I':
	case 'i':	goto yy231;
	default:	goto yy215;
	}
yy228:
	yych = *++cur;
	switch (yych) {
	case 'S':
	case 's':	goto yy232;
	default:	goto yy215;
	}
yy229:
	yych = *++cur;
	switch (yych) {
	case 'V':
	case 'v':	goto yy233;
	default:	goto yy215;
	}
yy230:
	yych = *++cur;
	switch (yych) {
	case 'D':	goto yy234;
	default:	goto yy215;
	}
yy231:
	yych = *++cur;
	switch (yych) {
	case 'O':
	case 'o':	goto yy235;
	default:	goto yy215;
	}
yy232:
	yych = *++cur;
	switch (yych) {
	case 'A':
	case 'a':	goto yy236;
	default:	goto yy215;
	}
yy233:
	yych = *++cur;
	switch (yych) {
	case 'I':
	case 'i':	goto yy237;
	default:	goto yy215;
	}
yy234:
	yych = *++cur;
	switch (yych) {
	case ' ':	goto yy238;
	default:	goto yy215;
	}
yy235:
	yych = *++cur;
	switch (yych) {
	case 'N':
	case 'n':	goto yy239;
	default:	goto yy215;
	}
yy236:
	yych = *++cur;
	switch (yych) {
	case 'G':
	case 'g':	goto yy240;
	default:	goto yy215;
	}
yy237:
	yych = *++cur;
	switch (yych) {
	case 'L':
	case 'l':	goto yy241;
	default:	goto yy215;
	}
yy238:
	yych = *++cur;
	switch (yych) {
	case 'C':	goto yy242;
	default:	goto yy215;
	}
yy239:
	yych = *++cur;
	switch (yych) {
	case 'I':
	case 'i':	goto yy243;
	default:	goto yy215;
	}
yy240:
	yych = *++cur;
	switch (yych) {
	case 'E':
	case 'e':	goto yy244;
	default:	goto yy215;
	}
yy241:
	yych = *++cur;
	switch (yych) {
	case 'E':
	case 'e':	goto yy245;
	default:	goto yy215;
	}
yy242:
	yych = *++cur;
	switch (yych) {
	case 'O':	goto yy246;
	default:	goto yy215;
	}
yy243:
	yych = *++cur;
	switch (yych) {
	case 'D':
	case 'd':	goto yy247;
	default:	goto yy215;
	}
yy244:
	yych = *++cur;
	switch (yych) {
	case ':':	goto yy248;
	default:	goto yy215;
	}
yy245:
	yych = *++cur;
	switch (yych) {
	case 'G':
	case 'g':	goto yy250;
	default:	goto yy215;
	}
yy246:
	yych = *++cur;
	switch (yych) {
	case 'M':	goto yy251;
	default:	goto yy215;
	}
yy247:
	yych = *++cur;
	switch (yych) {
	case ':':	goto yy252;
	default:	goto yy215;
	}
yy248:
	yych = *++cur;
	switch (yych) {
	case '\n':	goto yy216;
	case '\r':	goto yy254;
	default:	goto yy248;
	}
yy250:
	yych = *++cur;
	switch (yych) {
	case 'E':
	case 'e':	goto yy256;
	default:	goto yy215;
	}
yy251:
	yych = *++cur;
	switch (yych) {
	case 'M':	goto yy257;
	default:	goto yy215;
	}
yy252:
	yych = *++cur;
	switch (yych) {
	case '\n':	goto yy216;
	case '\r':	goto yy258;
	default:	goto yy252;
	}
yy254:
	yych = *++cur;
	switch (yych) {
	case '\n':	goto yy260;
	case '\r':	goto yy254;
	default:	goto yy248;
	}
yy256:
	yych = *++cur;
	switch (yych) {
	case ':':	goto yy262;
	default:	goto yy215;
	}
yy257:
	yych = *++cur;
	switch (yych) {
	case 'A':	goto yy264;
	default:	goto yy215;
	}
yy258:
	yych = *++cur;
	switch (yych) {
	case '\n':	goto yy265;
	case '\r':	goto yy258;
	default:	goto yy252;
	}
yy260:
	++cur;
#line 165 "src/lib/amipack_parse.re"
	{ CMD_HEADER(8, "Message"); }
#line 2012 "src/lib/amipack_parse.c"
yy262:
	yych = *++cur;
	switch (yych) {
	case '\n':	goto yy216;
	case '\r':	goto yy267;
	default:	goto yy262;
	}
yy264:
	yych = *++cur;
	switch (yych) {
	case 'N':	goto yy269;
	default:	goto yy215;
	}
yy265:
	++cur;
#line 164 "src/lib/amipack_parse.re"
	{ CMD_HEADER(9, "ActionID"); }
#line 2030 "src/lib/amipack_parse.c"
yy267:
	yych = *++cur;
	switch (yych) {
	case '\n':	goto yy270;
	case '\r':	goto yy267;
	default:	goto yy262;
	}
yy269:
	yych = *++cur;
	switch (yych) {
	case 'D':	goto yy272;
	default:	goto yy215;
	}
yy270:
	++cur;
#line 163 "src/lib/amipack_parse.re"
	{ CMD_HEADER(10, "Privilege"); }
#line 2048 "src/lib/amipack_parse.c"
yy272:
	yych = *++cur;
	switch (yych) {
	case '-':	goto yy273;
	default:	goto yy215;
	}
yy273:
	yych = *++cur;
	switch (yych) {
	case '-':	goto yy274;
	default:	goto yy215;
	}
yy274:
	yych = *++cur;
	switch (yych) {
	case '\r':	goto yy275;
	default:	goto yy215;
	}
yy275:
	yych = *++cur;
	switch (yych) {
	case '\n':	goto yy276;
	default:	goto yy214;
	}
yy276:
	yych = *(marker = ++cur);
	switch (yych) {
	case '\r':	goto yy277;
	default:	goto yy217;
	}
yy277:
	yych = *++cur;
	switch (yych) {
	case '\n':	goto yy279;
	default:	goto yy278;
	}
yy278:
	cur = marker;
	goto yy217;
yy279:
	++cur;
#line 168 "src/lib/amipack_parse.re"
	{
              len = cur - tok - 19; // output minus command end tag
              char *val = strndup(tok, len);
              amipack_append (pack, strdup("Output"), 6, val, len);
              goto done;
            }
#line 2097 "src/lib/amipack_parse.c"
}
#line 192 "src/lib/amipack_parse.re"


done:
  return pack;
}
