/* Generated by re2c 1.0.2 */
#line 1 "src/lib/amipack_parse.re"
/**
 * amiws -- Library with functions for read/create AMI packets
 * Copyright (C) 2016, Stas Kobzar <staskobzar@modulis.ca>
 *
 * This file is part of amiws.
 *
 * amiws is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * amiws is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with amiws.  If not, see <http://www.gnu.org/licenses/>.
 */

/**
 * @file amipack_parse.c
 * @brief AMI (Asterisk Management Interface) packet parser.
 *
 * @author Stas Kobzar <stas.kobzar@modulis.ca>
 */

#include <stdio.h>
#include <string.h>
#include "amipack.h"

/**
 * Commands to run when known header parsed.
 * @param name    Header type
 */
#define SET_HEADER(name)  len = cur - tok; \
                          hdr_name = strdup(name); \
                          goto yyc_key;

/**
 * Commands to run on Command AMI response header.
 * @param offset  Header name offset
 * @param name    Header type
 */
#define CMD_HEADER(offset, name) len = cur - tok - offset; tok += offset; \
                          while(*tok == ' ') { tok++; len--; } \
                          len -= 2; \
                          char *val = strndup(tok, len); \
                          amipack_append (pack, strdup(name), strlen(name), val, len); \
                          tok = cur; goto yyc_command;

// introducing types:re2c for AMI packet
/*! re2c parcing conditions. */
enum yycond_pack {
  yyckey,
  yycvalue,
  yyccommand,
  yycqueue,
  yycqmembers,
  yycqcallers
};

AMIPacket *amiparse_pack (const char *pack_str)
{
  AMIPacket *pack = amipack_init ();
  AMIQueue  *queue = pack->queue;
  const char *marker = pack_str;
  const char *cur    = marker;
  const char *ctxmarker;
  int c = yyckey;
  int len = 0;

  const char *yyt1;
const char *yyt2;
const char *yyt3;


  const char *tok = marker;
  char *hdr_name;
  // stags
  const char *tq1, *tq2, *tq3, *tq4, *tq5, *tq6;


#line 87 "src/lib/amipack_parse.c"
{
	unsigned char yych;
	unsigned int yyaccept = 0;
	switch (c) {
	case yyckey: goto yyc_key;
	case yycvalue: goto yyc_value;
	case yyccommand: goto yyc_command;
	case yycqueue: goto yyc_queue;
	case yycqmembers: goto yyc_qmembers;
	case yycqcallers: goto yyc_qcallers;
	}
/* *********************************** */
yyc_key:
	yych = *cur;
	switch (yych) {
	case '\r':
		yyt1 = cur;
		goto yy6;
	case ' ':	goto yy7;
	case ':':
		yyt1 = cur;
		goto yy9;
	case 'A':
	case 'a':
		yyt1 = cur;
		goto yy11;
	case 'E':
	case 'e':
		yyt1 = cur;
		goto yy12;
	case 'R':
	case 'r':
		yyt1 = cur;
		goto yy13;
	default:
		yyt1 = cur;
		goto yy3;
	}
yy3:
	yyaccept = 0;
	yych = *(marker = ++cur);
yy4:
	switch (yych) {
	case ' ':	goto yy14;
	case ':':	goto yy16;
	default:	goto yy3;
	}
yy5:
#line 152 "src/lib/amipack_parse.re"
	{
              len = cur - tok;
              hdr_name = strndup(tok, len);
              goto yyc_key;
            }
#line 142 "src/lib/amipack_parse.c"
yy6:
	yyaccept = 0;
	yych = *(marker = ++cur);
	switch (yych) {
	case '\n':	goto yy18;
	default:	goto yy4;
	}
yy7:
	++cur;
#line 106 "src/lib/amipack_parse.re"
	{
              printf("====== UNKNOWN ERROR =====\n");
              if (hdr_name) free (hdr_name);
              amipack_destroy (pack);
              return NULL;
            }
#line 159 "src/lib/amipack_parse.c"
yy9:
	yyaccept = 1;
	yych = *(marker = ++cur);
	switch (yych) {
	case '\r':	goto yy19;
	case ' ':	goto yy20;
	default:	goto yy16;
	}
yy10:
#line 121 "src/lib/amipack_parse.re"
	{ tok = cur; goto yyc_value; }
#line 171 "src/lib/amipack_parse.c"
yy11:
	yyaccept = 0;
	yych = *(marker = ++cur);
	switch (yych) {
	case 'C':
	case 'c':	goto yy21;
	default:	goto yy4;
	}
yy12:
	yyaccept = 0;
	yych = *(marker = ++cur);
	switch (yych) {
	case 'V':
	case 'v':	goto yy22;
	default:	goto yy4;
	}
yy13:
	yyaccept = 0;
	yych = *(marker = ++cur);
	switch (yych) {
	case 'E':
	case 'e':	goto yy23;
	default:	goto yy4;
	}
yy14:
	yych = *++cur;
	switch (yych) {
	case 'h':	goto yy24;
	default:	goto yy15;
	}
yy15:
	cur = marker;
	switch (yyaccept) {
	case 0: 	goto yy5;
	case 1: 	goto yy10;
	case 2: 	goto yy35;
	case 3: 	goto yy38;
	case 4: 	goto yy45;
	case 5: 	goto yy50;
	case 6: 	goto yy55;
	case 7: 	goto yy62;
	default:	goto yy94;
	}
yy16:
	yych = *++cur;
yy17:
	switch (yych) {
	case ' ':	goto yy14;
	default:	goto yy16;
	}
yy18:
	yyaccept = 0;
	yych = *(marker = ++cur);
	switch (yych) {
	case '\r':	goto yy25;
	default:	goto yy4;
	}
yy19:
	yych = *++cur;
	switch (yych) {
	case '\n':	goto yy26;
	default:	goto yy17;
	}
yy20:
	yyaccept = 1;
	yych = *(marker = ++cur);
	switch (yych) {
	case 'h':	goto yy24;
	default:	goto yy29;
	}
yy21:
	yyaccept = 0;
	yych = *(marker = ++cur);
	switch (yych) {
	case 'T':
	case 't':	goto yy30;
	default:	goto yy4;
	}
yy22:
	yyaccept = 0;
	yych = *(marker = ++cur);
	switch (yych) {
	case 'E':
	case 'e':	goto yy31;
	default:	goto yy4;
	}
yy23:
	yyaccept = 0;
	yych = *(marker = ++cur);
	switch (yych) {
	case 'S':
	case 's':	goto yy32;
	default:	goto yy4;
	}
yy24:
	yych = *++cur;
	switch (yych) {
	case 'a':	goto yy33;
	default:	goto yy15;
	}
yy25:
	yyaccept = 0;
	yych = *(marker = ++cur);
	switch (yych) {
	case '\n':	goto yy34;
	default:	goto yy4;
	}
yy26:
	yych = *++cur;
	switch (yych) {
	case '\r':	goto yy36;
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy37;
	default:	goto yy17;
	}
yy27:
	yych = *++cur;
	switch (yych) {
	case '\n':	goto yy39;
	default:	goto yy15;
	}
yy28:
	yyaccept = 1;
	yych = *(marker = ++cur);
yy29:
	switch (yych) {
	case '\r':	goto yy27;
	case ' ':	goto yy28;
	default:	goto yy10;
	}
yy30:
	yyaccept = 0;
	yych = *(marker = ++cur);
	switch (yych) {
	case 'I':
	case 'i':	goto yy40;
	default:	goto yy4;
	}
yy31:
	yyaccept = 0;
	yych = *(marker = ++cur);
	switch (yych) {
	case 'N':
	case 'n':	goto yy41;
	default:	goto yy4;
	}
yy32:
	yyaccept = 0;
	yych = *(marker = ++cur);
	switch (yych) {
	case 'P':
	case 'p':	goto yy42;
	default:	goto yy4;
	}
yy33:
	yych = *++cur;
	switch (yych) {
	case 's':	goto yy43;
	default:	goto yy15;
	}
yy34:
	yyaccept = 2;
	yych = *(marker = ++cur);
	goto yy4;
yy35:
#line 112 "src/lib/amipack_parse.re"
	{ goto done; }
#line 389 "src/lib/amipack_parse.c"
yy36:
	yych = *++cur;
	switch (yych) {
	case '\n':	goto yy44;
	default:	goto yy17;
	}
yy37:
	yyaccept = 3;
	yych = *(marker = ++cur);
	goto yy17;
yy38:
	cur -= 1;
#line 122 "src/lib/amipack_parse.re"
	{
              tok = cur;
              amipack_append(pack, hdr_name, strlen(hdr_name), strdup(""), 0);
              goto yyc_key;
            }
#line 408 "src/lib/amipack_parse.c"
yy39:
	yych = *++cur;
	switch (yych) {
	case '\r':	goto yy46;
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy47;
	default:	goto yy15;
	}
yy40:
	yyaccept = 0;
	yych = *(marker = ++cur);
	switch (yych) {
	case 'O':
	case 'o':	goto yy48;
	default:	goto yy4;
	}
yy41:
	yyaccept = 0;
	yych = *(marker = ++cur);
	switch (yych) {
	case 'T':
	case 't':	goto yy49;
	default:	goto yy4;
	}
yy42:
	yyaccept = 0;
	yych = *(marker = ++cur);
	switch (yych) {
	case 'O':
	case 'o':	goto yy51;
	default:	goto yy4;
	}
yy43:
	yych = *++cur;
	switch (yych) {
	case ' ':	goto yy52;
	default:	goto yy15;
	}
yy44:
	yyaccept = 4;
	yych = *(marker = ++cur);
	goto yy17;
yy45:
#line 127 "src/lib/amipack_parse.re"
	{
              tok = cur;
              amipack_append(pack, hdr_name, strlen(hdr_name), strdup(""), 0);
              goto done;
            }
#line 508 "src/lib/amipack_parse.c"
yy46:
	yych = *++cur;
	switch (yych) {
	case '\n':	goto yy53;
	default:	goto yy15;
	}
yy47:
	++cur;
	goto yy38;
yy48:
	yyaccept = 0;
	yych = *(marker = ++cur);
	switch (yych) {
	case 'N':
	case 'n':	goto yy54;
	default:	goto yy4;
	}
yy49:
	yyaccept = 5;
	yych = *(marker = ++cur);
	goto yy4;
yy50:
#line 147 "src/lib/amipack_parse.re"
	{
              amipack_type (pack, AMI_EVENT);
              SET_HEADER("Event");
            }
#line 536 "src/lib/amipack_parse.c"
yy51:
	yyaccept = 0;
	yych = *(marker = ++cur);
	switch (yych) {
	case 'N':
	case 'n':	goto yy56;
	default:	goto yy4;
	}
yy52:
	yych = *++cur;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
		yyt2 = cur;
		goto yy57;
	default:	goto yy15;
	}
yy53:
	++cur;
	goto yy45;
yy54:
	yyaccept = 6;
	yych = *(marker = ++cur);
	goto yy4;
yy55:
#line 143 "src/lib/amipack_parse.re"
	{
              amipack_type (pack, AMI_ACTION);
              SET_HEADER("Action");
            }
#line 575 "src/lib/amipack_parse.c"
yy56:
	yyaccept = 0;
	yych = *(marker = ++cur);
	switch (yych) {
	case 'S':
	case 's':	goto yy59;
	default:	goto yy4;
	}
yy57:
	yych = *++cur;
	switch (yych) {
	case ' ':	goto yy60;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy57;
	default:	goto yy15;
	}
yy59:
	yyaccept = 0;
	yych = *(marker = ++cur);
	switch (yych) {
	case 'E':
	case 'e':	goto yy61;
	default:	goto yy4;
	}
yy60:
	yych = *++cur;
	switch (yych) {
	case 'c':	goto yy63;
	default:	goto yy15;
	}
yy61:
	yyaccept = 7;
	yych = *(marker = ++cur);
	switch (yych) {
	case ':':	goto yy64;
	default:	goto yy4;
	}
yy62:
#line 139 "src/lib/amipack_parse.re"
	{
              amipack_type (pack, AMI_RESPONSE);
              SET_HEADER("Response");
            }
#line 627 "src/lib/amipack_parse.c"
yy63:
	yych = *++cur;
	switch (yych) {
	case 'a':	goto yy65;
	default:	goto yy15;
	}
yy64:
	yych = *++cur;
	switch (yych) {
	case ' ':	goto yy66;
	case 'F':
	case 'f':	goto yy67;
	default:	goto yy16;
	}
yy65:
	yych = *++cur;
	switch (yych) {
	case 'l':	goto yy68;
	default:	goto yy15;
	}
yy66:
	yych = *++cur;
	switch (yych) {
	case 'h':	goto yy24;
	default:	goto yy70;
	}
yy67:
	yych = *++cur;
	switch (yych) {
	case 'O':
	case 'o':	goto yy72;
	default:	goto yy17;
	}
yy68:
	yych = *++cur;
	switch (yych) {
	case 'l':	goto yy73;
	default:	goto yy15;
	}
yy69:
	yych = *++cur;
yy70:
	switch (yych) {
	case ' ':	goto yy69;
	case 'F':
	case 'f':	goto yy71;
	default:	goto yy15;
	}
yy71:
	yych = *++cur;
	switch (yych) {
	case 'O':
	case 'o':	goto yy74;
	default:	goto yy15;
	}
yy72:
	yych = *++cur;
	switch (yych) {
	case 'L':
	case 'l':	goto yy75;
	default:	goto yy17;
	}
yy73:
	yych = *++cur;
	switch (yych) {
	case 's':	goto yy76;
	default:	goto yy15;
	}
yy74:
	yych = *++cur;
	switch (yych) {
	case 'L':
	case 'l':	goto yy77;
	default:	goto yy15;
	}
yy75:
	yych = *++cur;
	switch (yych) {
	case 'L':
	case 'l':	goto yy78;
	default:	goto yy17;
	}
yy76:
	yych = *++cur;
	switch (yych) {
	case ' ':	goto yy79;
	default:	goto yy15;
	}
yy77:
	yych = *++cur;
	switch (yych) {
	case 'L':
	case 'l':	goto yy80;
	default:	goto yy15;
	}
yy78:
	yych = *++cur;
	switch (yych) {
	case 'O':
	case 'o':	goto yy81;
	default:	goto yy17;
	}
yy79:
	yych = *++cur;
	switch (yych) {
	case '(':	goto yy82;
	default:	goto yy15;
	}
yy80:
	yych = *++cur;
	switch (yych) {
	case 'O':
	case 'o':	goto yy83;
	default:	goto yy15;
	}
yy81:
	yych = *++cur;
	switch (yych) {
	case 'W':
	case 'w':	goto yy84;
	default:	goto yy17;
	}
yy82:
	yych = *++cur;
	switch (yych) {
	case 'm':	goto yy85;
	default:	goto yy15;
	}
yy83:
	yych = *++cur;
	switch (yych) {
	case 'W':
	case 'w':	goto yy86;
	default:	goto yy15;
	}
yy84:
	yych = *++cur;
	switch (yych) {
	case 'S':
	case 's':	goto yy87;
	default:	goto yy17;
	}
yy85:
	yych = *++cur;
	switch (yych) {
	case 'a':	goto yy88;
	default:	goto yy15;
	}
yy86:
	yych = *++cur;
	switch (yych) {
	case 'S':
	case 's':	goto yy89;
	default:	goto yy15;
	}
yy87:
	yych = *++cur;
	switch (yych) {
	case '\r':	goto yy90;
	default:	goto yy17;
	}
yy88:
	yych = *++cur;
	switch (yych) {
	case 'x':	goto yy91;
	default:	goto yy15;
	}
yy89:
	yych = *++cur;
	switch (yych) {
	case '\r':	goto yy92;
	default:	goto yy15;
	}
yy90:
	yych = *++cur;
	switch (yych) {
	case '\n':	goto yy93;
	default:	goto yy17;
	}
yy91:
	yych = *++cur;
	switch (yych) {
	case ' ':	goto yy95;
	default:	goto yy15;
	}
yy92:
	yych = *++cur;
	switch (yych) {
	case '\n':	goto yy96;
	default:	goto yy15;
	}
yy93:
	yyaccept = 8;
	yych = *(marker = ++cur);
	goto yy17;
yy94:
#line 132 "src/lib/amipack_parse.re"
	{
              len = cur - tok;
              tok = cur;
              amipack_type (pack, AMI_RESPONSE);
              amipack_append(pack, strdup("Response"), 8, strdup("Follows"), 7);
              goto yyc_command;
            }
#line 832 "src/lib/amipack_parse.c"
yy95:
	yych = *++cur;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':
		yyt3 = cur;
		goto yy97;
	default:	goto yy15;
	}
yy96:
	++cur;
	goto yy94;
yy97:
	yych = *++cur;
	switch (yych) {
	case ')':	goto yy99;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy97;
	default:	goto yy15;
	}
yy99:
	yych = *++cur;
	switch (yych) {
	case ' ':	goto yy100;
	default:	goto yy15;
	}
yy100:
	++cur;
	tq1 = yyt1;
	tq3 = yyt2;
	tq5 = yyt3;
	tq2 = yyt2 - 5;
	tq4 = yyt3 - 12;
	tq6 = cur - 2;
#line 114 "src/lib/amipack_parse.re"
	{
              queue->name = strndup(tq1, (int)(tq2 - tq1));
              queue->calls = (int)strtol(tq3, NULL, 10);
              queue->maxlen = (int)strtol(tq5, NULL, 10);
              amipack_type (pack, AMI_QUEUES);
              goto yyc_queue;
            }
#line 943 "src/lib/amipack_parse.c"
/* *********************************** */
yyc_value:
	yych = *cur;
	switch (yych) {
	case '\n':	goto yy107;
	case '\r':	goto yy109;
	default:	goto yy104;
	}
yy104:
	yych = *++cur;
	switch (yych) {
	case '\n':
	case '\r':	goto yy106;
	default:	goto yy104;
	}
yy106:
#line 159 "src/lib/amipack_parse.re"
	{
              len = cur - tok;
              char *val = strndup(tok, len);
              amipack_append(pack, hdr_name, strlen(hdr_name), val, len);
              goto yyc_value;
            }
#line 967 "src/lib/amipack_parse.c"
yy107:
	++cur;
yy108:
#line 106 "src/lib/amipack_parse.re"
	{
              printf("====== UNKNOWN ERROR =====\n");
              if (hdr_name) free (hdr_name);
              amipack_destroy (pack);
              return NULL;
            }
#line 978 "src/lib/amipack_parse.c"
yy109:
	yych = *(marker = ++cur);
	switch (yych) {
	case '\n':	goto yy110;
	default:	goto yy108;
	}
yy110:
	yych = *++cur;
	switch (yych) {
	case '\r':	goto yy112;
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy113;
	default:	goto yy111;
	}
yy111:
	cur = marker;
	goto yy108;
yy112:
	yych = *++cur;
	switch (yych) {
	case '\n':	goto yy115;
	default:	goto yy111;
	}
yy113:
	++cur;
	cur -= 1;
#line 158 "src/lib/amipack_parse.re"
	{ tok = cur; goto yyc_key; }
#line 1057 "src/lib/amipack_parse.c"
yy115:
	++cur;
#line 112 "src/lib/amipack_parse.re"
	{ goto done; }
#line 1062 "src/lib/amipack_parse.c"
/* *********************************** */
yyc_command:
	yych = *cur;
	switch (yych) {
	case '\n':	goto yy121;
	case '-':	goto yy123;
	case 'A':
	case 'a':	goto yy124;
	case 'M':
	case 'm':	goto yy125;
	case 'P':
	case 'p':	goto yy126;
	default:	goto yy119;
	}
yy119:
	yych = *++cur;
yy120:
	switch (yych) {
	case '\n':	goto yy121;
	default:	goto yy119;
	}
yy121:
	++cur;
yy122:
#line 170 "src/lib/amipack_parse.re"
	{ goto yyc_command; }
#line 1089 "src/lib/amipack_parse.c"
yy123:
	yych = *++cur;
	switch (yych) {
	case '-':	goto yy127;
	default:	goto yy120;
	}
yy124:
	yych = *++cur;
	switch (yych) {
	case 'C':
	case 'c':	goto yy128;
	default:	goto yy120;
	}
yy125:
	yych = *++cur;
	switch (yych) {
	case 'E':
	case 'e':	goto yy129;
	default:	goto yy120;
	}
yy126:
	yych = *++cur;
	switch (yych) {
	case 'R':
	case 'r':	goto yy130;
	default:	goto yy120;
	}
yy127:
	yych = *++cur;
	switch (yych) {
	case 'E':	goto yy131;
	default:	goto yy120;
	}
yy128:
	yych = *++cur;
	switch (yych) {
	case 'T':
	case 't':	goto yy132;
	default:	goto yy120;
	}
yy129:
	yych = *++cur;
	switch (yych) {
	case 'S':
	case 's':	goto yy133;
	default:	goto yy120;
	}
yy130:
	yych = *++cur;
	switch (yych) {
	case 'I':
	case 'i':	goto yy134;
	default:	goto yy120;
	}
yy131:
	yych = *++cur;
	switch (yych) {
	case 'N':	goto yy135;
	default:	goto yy120;
	}
yy132:
	yych = *++cur;
	switch (yych) {
	case 'I':
	case 'i':	goto yy136;
	default:	goto yy120;
	}
yy133:
	yych = *++cur;
	switch (yych) {
	case 'S':
	case 's':	goto yy137;
	default:	goto yy120;
	}
yy134:
	yych = *++cur;
	switch (yych) {
	case 'V':
	case 'v':	goto yy138;
	default:	goto yy120;
	}
yy135:
	yych = *++cur;
	switch (yych) {
	case 'D':	goto yy139;
	default:	goto yy120;
	}
yy136:
	yych = *++cur;
	switch (yych) {
	case 'O':
	case 'o':	goto yy140;
	default:	goto yy120;
	}
yy137:
	yych = *++cur;
	switch (yych) {
	case 'A':
	case 'a':	goto yy141;
	default:	goto yy120;
	}
yy138:
	yych = *++cur;
	switch (yych) {
	case 'I':
	case 'i':	goto yy142;
	default:	goto yy120;
	}
yy139:
	yych = *++cur;
	switch (yych) {
	case ' ':	goto yy143;
	default:	goto yy120;
	}
yy140:
	yych = *++cur;
	switch (yych) {
	case 'N':
	case 'n':	goto yy144;
	default:	goto yy120;
	}
yy141:
	yych = *++cur;
	switch (yych) {
	case 'G':
	case 'g':	goto yy145;
	default:	goto yy120;
	}
yy142:
	yych = *++cur;
	switch (yych) {
	case 'L':
	case 'l':	goto yy146;
	default:	goto yy120;
	}
yy143:
	yych = *++cur;
	switch (yych) {
	case 'C':	goto yy147;
	default:	goto yy120;
	}
yy144:
	yych = *++cur;
	switch (yych) {
	case 'I':
	case 'i':	goto yy148;
	default:	goto yy120;
	}
yy145:
	yych = *++cur;
	switch (yych) {
	case 'E':
	case 'e':	goto yy149;
	default:	goto yy120;
	}
yy146:
	yych = *++cur;
	switch (yych) {
	case 'E':
	case 'e':	goto yy150;
	default:	goto yy120;
	}
yy147:
	yych = *++cur;
	switch (yych) {
	case 'O':	goto yy151;
	default:	goto yy120;
	}
yy148:
	yych = *++cur;
	switch (yych) {
	case 'D':
	case 'd':	goto yy152;
	default:	goto yy120;
	}
yy149:
	yych = *++cur;
	switch (yych) {
	case ':':	goto yy153;
	default:	goto yy120;
	}
yy150:
	yych = *++cur;
	switch (yych) {
	case 'G':
	case 'g':	goto yy155;
	default:	goto yy120;
	}
yy151:
	yych = *++cur;
	switch (yych) {
	case 'M':	goto yy156;
	default:	goto yy120;
	}
yy152:
	yych = *++cur;
	switch (yych) {
	case ':':	goto yy157;
	default:	goto yy120;
	}
yy153:
	yych = *++cur;
	switch (yych) {
	case '\n':	goto yy121;
	case '\r':	goto yy159;
	default:	goto yy153;
	}
yy155:
	yych = *++cur;
	switch (yych) {
	case 'E':
	case 'e':	goto yy161;
	default:	goto yy120;
	}
yy156:
	yych = *++cur;
	switch (yych) {
	case 'M':	goto yy162;
	default:	goto yy120;
	}
yy157:
	yych = *++cur;
	switch (yych) {
	case '\n':	goto yy121;
	case '\r':	goto yy163;
	default:	goto yy157;
	}
yy159:
	yych = *++cur;
	switch (yych) {
	case '\n':	goto yy165;
	case '\r':	goto yy159;
	default:	goto yy153;
	}
yy161:
	yych = *++cur;
	switch (yych) {
	case ':':	goto yy167;
	default:	goto yy120;
	}
yy162:
	yych = *++cur;
	switch (yych) {
	case 'A':	goto yy169;
	default:	goto yy120;
	}
yy163:
	yych = *++cur;
	switch (yych) {
	case '\n':	goto yy170;
	case '\r':	goto yy163;
	default:	goto yy157;
	}
yy165:
	++cur;
#line 168 "src/lib/amipack_parse.re"
	{ CMD_HEADER(8, "Message"); }
#line 1347 "src/lib/amipack_parse.c"
yy167:
	yych = *++cur;
	switch (yych) {
	case '\n':	goto yy121;
	case '\r':	goto yy172;
	default:	goto yy167;
	}
yy169:
	yych = *++cur;
	switch (yych) {
	case 'N':	goto yy174;
	default:	goto yy120;
	}
yy170:
	++cur;
#line 167 "src/lib/amipack_parse.re"
	{ CMD_HEADER(9, "ActionID"); }
#line 1365 "src/lib/amipack_parse.c"
yy172:
	yych = *++cur;
	switch (yych) {
	case '\n':	goto yy175;
	case '\r':	goto yy172;
	default:	goto yy167;
	}
yy174:
	yych = *++cur;
	switch (yych) {
	case 'D':	goto yy177;
	default:	goto yy120;
	}
yy175:
	++cur;
#line 166 "src/lib/amipack_parse.re"
	{ CMD_HEADER(10, "Privilege"); }
#line 1383 "src/lib/amipack_parse.c"
yy177:
	yych = *++cur;
	switch (yych) {
	case '-':	goto yy178;
	default:	goto yy120;
	}
yy178:
	yych = *++cur;
	switch (yych) {
	case '-':	goto yy179;
	default:	goto yy120;
	}
yy179:
	yych = *++cur;
	switch (yych) {
	case '\r':	goto yy180;
	default:	goto yy120;
	}
yy180:
	yych = *++cur;
	switch (yych) {
	case '\n':	goto yy181;
	default:	goto yy119;
	}
yy181:
	yych = *(marker = ++cur);
	switch (yych) {
	case '\r':	goto yy182;
	default:	goto yy122;
	}
yy182:
	yych = *++cur;
	switch (yych) {
	case '\n':	goto yy184;
	default:	goto yy183;
	}
yy183:
	cur = marker;
	goto yy122;
yy184:
	++cur;
#line 171 "src/lib/amipack_parse.re"
	{
              len = cur - tok - 19; // output minus command end tag
              char *val = strndup(tok, len);
              amipack_append (pack, strdup("Output"), 6, val, len);
              goto done;
            }
#line 1432 "src/lib/amipack_parse.c"
/* *********************************** */
yyc_queue:
	yych = *cur;
	switch (yych) {
	case ' ':	goto yy190;
	case 'S':	goto yy191;
	case 'W':	goto yy192;
	case 'i':	goto yy193;
	default:	goto yy188;
	}
yy188:
	++cur;
yy189:
#line 106 "src/lib/amipack_parse.re"
	{
              printf("====== UNKNOWN ERROR =====\n");
              if (hdr_name) free (hdr_name);
              amipack_destroy (pack);
              return NULL;
            }
#line 1453 "src/lib/amipack_parse.c"
yy190:
	yych = *(marker = ++cur);
	switch (yych) {
	case ' ':	goto yy194;
	default:	goto yy189;
	}
yy191:
	yych = *(marker = ++cur);
	switch (yych) {
	case 'L':	goto yy196;
	default:	goto yy189;
	}
yy192:
	yych = *(marker = ++cur);
	switch (yych) {
	case ':':	goto yy197;
	default:	goto yy189;
	}
yy193:
	yych = *(marker = ++cur);
	switch (yych) {
	case 'n':	goto yy198;
	default:	goto yy189;
	}
yy194:
	yych = *++cur;
	switch (yych) {
	case ' ':	goto yy199;
	default:	goto yy195;
	}
yy195:
	cur = marker;
	goto yy189;
yy196:
	yych = *++cur;
	switch (yych) {
	case ':':	goto yy200;
	default:	goto yy195;
	}
yy197:
	yych = *++cur;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
		yyt1 = cur;
		goto yy201;
	default:	goto yy195;
	}
yy198:
	yych = *++cur;
	switch (yych) {
	case ' ':	goto yy203;
	default:	goto yy195;
	}
yy199:
	yych = *++cur;
	switch (yych) {
	case 'C':	goto yy204;
	case 'M':	goto yy205;
	case 'N':	goto yy206;
	default:	goto yy195;
	}
yy200:
	yych = *++cur;
	switch (yych) {
	case '.':
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
		yyt1 = cur;
		goto yy207;
	default:	goto yy195;
	}
yy201:
	yych = *++cur;
	switch (yych) {
	case ',':	goto yy209;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy201;
	default:	goto yy195;
	}
yy203:
	yych = *++cur;
	switch (yych) {
	case '\'':	goto yy210;
	default:	goto yy195;
	}
yy204:
	yych = *++cur;
	switch (yych) {
	case 'a':	goto yy211;
	default:	goto yy195;
	}
yy205:
	yych = *++cur;
	switch (yych) {
	case 'e':	goto yy212;
	default:	goto yy195;
	}
yy206:
	yych = *++cur;
	switch (yych) {
	case 'o':	goto yy213;
	default:	goto yy195;
	}
yy207:
	yych = *++cur;
	switch (yych) {
	case '%':	goto yy214;
	case '.':
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy207;
	default:	goto yy195;
	}
yy209:
	yych = *++cur;
	switch (yych) {
	case ' ':	goto yy215;
	default:	goto yy195;
	}
yy210:
	yych = *++cur;
	switch (yych) {
	case '\'':	goto yy195;
	default:
		yyt1 = cur;
		goto yy216;
	}
yy211:
	yych = *++cur;
	switch (yych) {
	case 'l':	goto yy218;
	default:	goto yy195;
	}
yy212:
	yych = *++cur;
	switch (yych) {
	case 'm':	goto yy219;
	default:	goto yy195;
	}
yy213:
	yych = *++cur;
	switch (yych) {
	case ' ':	goto yy220;
	default:	goto yy195;
	}
yy214:
	yych = *++cur;
	switch (yych) {
	case ' ':	goto yy221;
	default:	goto yy195;
	}
yy215:
	yych = *++cur;
	switch (yych) {
	case 'C':	goto yy222;
	default:	goto yy195;
	}
yy216:
	yych = *++cur;
	switch (yych) {
	case '\'':	goto yy223;
	default:	goto yy216;
	}
yy218:
	yych = *++cur;
	switch (yych) {
	case 'l':	goto yy224;
	default:	goto yy195;
	}
yy219:
	yych = *++cur;
	switch (yych) {
	case 'b':	goto yy225;
	default:	goto yy195;
	}
yy220:
	yych = *++cur;
	switch (yych) {
	case 'C':	goto yy226;
	case 'M':	goto yy227;
	default:	goto yy195;
	}
yy221:
	yych = *++cur;
	switch (yych) {
	case 'w':	goto yy228;
	default:	goto yy195;
	}
yy222:
	yych = *++cur;
	switch (yych) {
	case ':':	goto yy229;
	default:	goto yy195;
	}
yy223:
	yych = *++cur;
	switch (yych) {
	case ' ':	goto yy230;
	default:	goto yy195;
	}
yy224:
	yych = *++cur;
	switch (yych) {
	case 'e':	goto yy231;
	default:	goto yy195;
	}
yy225:
	yych = *++cur;
	switch (yych) {
	case 'e':	goto yy232;
	default:	goto yy195;
	}
yy226:
	yych = *++cur;
	switch (yych) {
	case 'a':	goto yy233;
	default:	goto yy195;
	}
yy227:
	yych = *++cur;
	switch (yych) {
	case 'e':	goto yy234;
	default:	goto yy195;
	}
yy228:
	yych = *++cur;
	switch (yych) {
	case 'i':	goto yy235;
	default:	goto yy195;
	}
yy229:
	yych = *++cur;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
		yyt2 = cur;
		goto yy236;
	default:	goto yy195;
	}
yy230:
	yych = *++cur;
	switch (yych) {
	case 's':	goto yy238;
	default:	goto yy195;
	}
yy231:
	yych = *++cur;
	switch (yych) {
	case 'r':	goto yy239;
	default:	goto yy195;
	}
yy232:
	yych = *++cur;
	switch (yych) {
	case 'r':	goto yy240;
	default:	goto yy195;
	}
yy233:
	yych = *++cur;
	switch (yych) {
	case 'l':	goto yy241;
	default:	goto yy195;
	}
yy234:
	yych = *++cur;
	switch (yych) {
	case 'm':	goto yy242;
	default:	goto yy195;
	}
yy235:
	yych = *++cur;
	switch (yych) {
	case 't':	goto yy243;
	default:	goto yy195;
	}
yy236:
	yych = *++cur;
	switch (yych) {
	case ',':	goto yy244;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy236;
	default:	goto yy195;
	}
yy238:
	yych = *++cur;
	switch (yych) {
	case 't':	goto yy245;
	default:	goto yy195;
	}
yy239:
	yych = *++cur;
	switch (yych) {
	case 's':	goto yy246;
	default:	goto yy195;
	}
yy240:
	yych = *++cur;
	switch (yych) {
	case 's':	goto yy247;
	default:	goto yy195;
	}
yy241:
	yych = *++cur;
	switch (yych) {
	case 'l':	goto yy248;
	default:	goto yy195;
	}
yy242:
	yych = *++cur;
	switch (yych) {
	case 'b':	goto yy249;
	default:	goto yy195;
	}
yy243:
	yych = *++cur;
	switch (yych) {
	case 'h':	goto yy250;
	default:	goto yy195;
	}
yy244:
	yych = *++cur;
	switch (yych) {
	case ' ':	goto yy251;
	default:	goto yy195;
	}
yy245:
	yych = *++cur;
	switch (yych) {
	case 'r':	goto yy252;
	default:	goto yy195;
	}
yy246:
	yych = *++cur;
	switch (yych) {
	case ':':	goto yy253;
	default:	goto yy195;
	}
yy247:
	yych = *++cur;
	switch (yych) {
	case ':':	goto yy254;
	default:	goto yy195;
	}
yy248:
	yych = *++cur;
	switch (yych) {
	case 'e':	goto yy255;
	default:	goto yy195;
	}
yy249:
	yych = *++cur;
	switch (yych) {
	case 'e':	goto yy256;
	default:	goto yy195;
	}
yy250:
	yych = *++cur;
	switch (yych) {
	case 'i':	goto yy257;
	default:	goto yy195;
	}
yy251:
	yych = *++cur;
	switch (yych) {
	case 'A':	goto yy258;
	default:	goto yy195;
	}
yy252:
	yych = *++cur;
	switch (yych) {
	case 'a':	goto yy259;
	default:	goto yy195;
	}
yy253:
	yych = *++cur;
	switch (yych) {
	case ' ':	goto yy260;
	default:	goto yy195;
	}
yy254:
	yych = *++cur;
	switch (yych) {
	case ' ':	goto yy261;
	default:	goto yy195;
	}
yy255:
	yych = *++cur;
	switch (yych) {
	case 'r':	goto yy262;
	default:	goto yy195;
	}
yy256:
	yych = *++cur;
	switch (yych) {
	case 'r':	goto yy263;
	default:	goto yy195;
	}
yy257:
	yych = *++cur;
	switch (yych) {
	case 'n':	goto yy264;
	default:	goto yy195;
	}
yy258:
	yych = *++cur;
	switch (yych) {
	case ':':	goto yy265;
	default:	goto yy195;
	}
yy259:
	yych = *++cur;
	switch (yych) {
	case 't':	goto yy266;
	default:	goto yy195;
	}
yy260:
	yych = *++cur;
	switch (yych) {
	case '\r':	goto yy267;
	default:	goto yy195;
	}
yy261:
	yych = *++cur;
	switch (yych) {
	case '\r':	goto yy268;
	default:	goto yy195;
	}
yy262:
	yych = *++cur;
	switch (yych) {
	case 's':	goto yy269;
	default:	goto yy195;
	}
yy263:
	yych = *++cur;
	switch (yych) {
	case 's':	goto yy270;
	default:	goto yy195;
	}
yy264:
	yych = *++cur;
	switch (yych) {
	case ' ':	goto yy271;
	default:	goto yy195;
	}
yy265:
	yych = *++cur;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
		yyt3 = cur;
		goto yy272;
	default:	goto yy195;
	}
yy266:
	yych = *++cur;
	switch (yych) {
	case 'e':	goto yy274;
	default:	goto yy195;
	}
yy267:
	yych = *++cur;
	switch (yych) {
	case '\n':	goto yy275;
	default:	goto yy195;
	}
yy268:
	yych = *++cur;
	switch (yych) {
	case '\n':	goto yy277;
	default:	goto yy195;
	}
yy269:
	yych = *++cur;
	switch (yych) {
	case '\r':	goto yy279;
	default:	goto yy195;
	}
yy270:
	yych = *++cur;
	switch (yych) {
	case '\r':	goto yy280;
	default:	goto yy195;
	}
yy271:
	yych = *++cur;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
		yyt2 = cur;
		goto yy281;
	default:	goto yy195;
	}
yy272:
	yych = *++cur;
	switch (yych) {
	case ',':	goto yy283;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy272;
	default:	goto yy195;
	}
yy274:
	yych = *++cur;
	switch (yych) {
	case 'g':	goto yy284;
	default:	goto yy195;
	}
yy275:
	++cur;
#line 208 "src/lib/amipack_parse.re"
	{
              queue->callers = calloc(QUEUE_LIST_LEN, QUEUE_ITEM_LEN);
              goto yyc_qcallers;
          }
#line 2040 "src/lib/amipack_parse.c"
yy277:
	++cur;
#line 204 "src/lib/amipack_parse.re"
	{
              queue->members = calloc(QUEUE_LIST_LEN, QUEUE_ITEM_LEN);
              goto yyc_qmembers;
          }
#line 2048 "src/lib/amipack_parse.c"
yy279:
	yych = *++cur;
	switch (yych) {
	case '\n':	goto yy285;
	default:	goto yy195;
	}
yy280:
	yych = *++cur;
	switch (yych) {
	case '\n':	goto yy286;
	default:	goto yy195;
	}
yy281:
	yych = *++cur;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy281;
	case 's':	goto yy288;
	default:	goto yy195;
	}
yy283:
	yych = *++cur;
	switch (yych) {
	case ' ':	goto yy289;
	default:	goto yy195;
	}
yy284:
	yych = *++cur;
	switch (yych) {
	case 'y':	goto yy291;
	default:	goto yy195;
	}
yy285:
	yych = *++cur;
	switch (yych) {
	case '\r':	goto yy292;
	default:	goto yy195;
	}
yy286:
	++cur;
#line 196 "src/lib/amipack_parse.re"
	{
              queue->members_size = 0;
              goto yyc_queue;
          }
#line 2102 "src/lib/amipack_parse.c"
yy288:
	yych = *++cur;
	switch (yych) {
	case '\r':	goto yy293;
	default:	goto yy195;
	}
yy289:
	++cur;
	tq1 = yyt1;
	tq3 = yyt2;
	tq5 = yyt3;
	tq2 = yyt2 - 4;
	tq4 = yyt3 - 4;
	tq6 = cur - 2;
#line 185 "src/lib/amipack_parse.re"
	{
              queue->weight = (int)strtol(tq1, NULL, 10);
              queue->callscompleted = (int)strtol(tq3, NULL, 10);
              queue->callsabandoned = (int)strtol(tq5, NULL, 10);
              goto yyc_queue;
          }
#line 2124 "src/lib/amipack_parse.c"
yy291:
	yych = *++cur;
	switch (yych) {
	case ' ':	goto yy294;
	default:	goto yy195;
	}
yy292:
	yych = *++cur;
	switch (yych) {
	case '\n':	goto yy295;
	default:	goto yy195;
	}
yy293:
	yych = *++cur;
	switch (yych) {
	case '\n':	goto yy297;
	default:	goto yy195;
	}
yy294:
	yych = *++cur;
	switch (yych) {
	case '(':	goto yy299;
	default:	goto yy195;
	}
yy295:
	++cur;
#line 200 "src/lib/amipack_parse.re"
	{
              queue->callers_size = 0;
              goto done;
          }
#line 2156 "src/lib/amipack_parse.c"
yy297:
	++cur;
	tq1 = yyt1;
	tq3 = yyt2;
	tq2 = yyt2 - 9;
	tq4 = cur - 3;
#line 191 "src/lib/amipack_parse.re"
	{
              queue->sl = strndup(tq1, (int)(tq2 - tq1));
              queue->sl_sec = (int)strtol(tq3, NULL, 10);
              goto yyc_queue;
          }
#line 2169 "src/lib/amipack_parse.c"
yy299:
	yych = *++cur;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
		yyt2 = cur;
		goto yy300;
	default:	goto yy195;
	}
yy300:
	yych = *++cur;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy300;
	case 's':	goto yy302;
	default:	goto yy195;
	}
yy302:
	yych = *++cur;
	switch (yych) {
	case ' ':	goto yy303;
	default:	goto yy195;
	}
yy303:
	yych = *++cur;
	switch (yych) {
	case 'h':	goto yy304;
	default:	goto yy195;
	}
yy304:
	yych = *++cur;
	switch (yych) {
	case 'o':	goto yy305;
	default:	goto yy195;
	}
yy305:
	yych = *++cur;
	switch (yych) {
	case 'l':	goto yy306;
	default:	goto yy195;
	}
yy306:
	yych = *++cur;
	switch (yych) {
	case 'd':	goto yy307;
	default:	goto yy195;
	}
yy307:
	yych = *++cur;
	switch (yych) {
	case 't':	goto yy308;
	default:	goto yy195;
	}
yy308:
	yych = *++cur;
	switch (yych) {
	case 'i':	goto yy309;
	default:	goto yy195;
	}
yy309:
	yych = *++cur;
	switch (yych) {
	case 'm':	goto yy310;
	default:	goto yy195;
	}
yy310:
	yych = *++cur;
	switch (yych) {
	case 'e':	goto yy311;
	default:	goto yy195;
	}
yy311:
	yych = *++cur;
	switch (yych) {
	case ',':	goto yy312;
	default:	goto yy195;
	}
yy312:
	yych = *++cur;
	switch (yych) {
	case ' ':	goto yy313;
	default:	goto yy195;
	}
yy313:
	yych = *++cur;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
		yyt3 = cur;
		goto yy314;
	default:	goto yy195;
	}
yy314:
	yych = *++cur;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy314;
	case 's':	goto yy316;
	default:	goto yy195;
	}
yy316:
	yych = *++cur;
	switch (yych) {
	case ' ':	goto yy317;
	default:	goto yy195;
	}
yy317:
	yych = *++cur;
	switch (yych) {
	case 't':	goto yy318;
	default:	goto yy195;
	}
yy318:
	yych = *++cur;
	switch (yych) {
	case 'a':	goto yy319;
	default:	goto yy195;
	}
yy319:
	yych = *++cur;
	switch (yych) {
	case 'l':	goto yy320;
	default:	goto yy195;
	}
yy320:
	yych = *++cur;
	switch (yych) {
	case 'k':	goto yy321;
	default:	goto yy195;
	}
yy321:
	yych = *++cur;
	switch (yych) {
	case 't':	goto yy322;
	default:	goto yy195;
	}
yy322:
	yych = *++cur;
	switch (yych) {
	case 'i':	goto yy323;
	default:	goto yy195;
	}
yy323:
	yych = *++cur;
	switch (yych) {
	case 'm':	goto yy324;
	default:	goto yy195;
	}
yy324:
	yych = *++cur;
	switch (yych) {
	case 'e':	goto yy325;
	default:	goto yy195;
	}
yy325:
	yych = *++cur;
	switch (yych) {
	case ')':	goto yy326;
	default:	goto yy195;
	}
yy326:
	yych = *++cur;
	switch (yych) {
	case ',':	goto yy327;
	default:	goto yy195;
	}
yy327:
	yych = *++cur;
	switch (yych) {
	case ' ':	goto yy328;
	default:	goto yy195;
	}
yy328:
	++cur;
	tq1 = yyt1;
	tq3 = yyt2;
	tq5 = yyt3;
	tq2 = yyt2 - 12;
	tq4 = yyt3 - 12;
	tq6 = cur - 13;
#line 179 "src/lib/amipack_parse.re"
	{
              queue->strategy = strndup(tq1, (int)(tq2 - tq1));
              queue->holdtime = (int)strtol(tq3, NULL, 10);
              queue->talktime = (int)strtol(tq5, NULL, 10);
              goto yyc_queue;
          }
#line 2389 "src/lib/amipack_parse.c"
/* *********************************** */
yyc_qmembers:
	yych = *cur;
	switch (yych) {
	case ' ':	goto yy334;
	default:	goto yy332;
	}
yy332:
	++cur;
yy333:
#line 106 "src/lib/amipack_parse.re"
	{
              printf("====== UNKNOWN ERROR =====\n");
              if (hdr_name) free (hdr_name);
              amipack_destroy (pack);
              return NULL;
            }
#line 2407 "src/lib/amipack_parse.c"
yy334:
	yych = *(marker = ++cur);
	switch (yych) {
	case ' ':	goto yy335;
	default:	goto yy333;
	}
yy335:
	yych = *++cur;
	switch (yych) {
	case ' ':	goto yy337;
	default:	goto yy336;
	}
yy336:
	cur = marker;
	goto yy333;
yy337:
	yych = *++cur;
	switch (yych) {
	case ' ':	goto yy338;
	case 'C':	goto yy339;
	case 'N':	goto yy340;
	default:	goto yy336;
	}
yy338:
	yych = *++cur;
	switch (yych) {
	case ' ':	goto yy341;
	default:	goto yy336;
	}
yy339:
	yych = *++cur;
	switch (yych) {
	case 'a':	goto yy342;
	default:	goto yy336;
	}
yy340:
	yych = *++cur;
	switch (yych) {
	case 'o':	goto yy343;
	default:	goto yy336;
	}
yy341:
	yych = *++cur;
	switch (yych) {
	case ' ':	goto yy344;
	default:	goto yy336;
	}
yy342:
	yych = *++cur;
	switch (yych) {
	case 'l':	goto yy345;
	default:	goto yy336;
	}
yy343:
	yych = *++cur;
	switch (yych) {
	case ' ':	goto yy346;
	default:	goto yy336;
	}
yy344:
	yych = *++cur;
	switch (yych) {
	case '@':	goto yy336;
	default:
		yyt1 = cur;
		goto yy347;
	}
yy345:
	yych = *++cur;
	switch (yych) {
	case 'l':	goto yy349;
	default:	goto yy336;
	}
yy346:
	yych = *++cur;
	switch (yych) {
	case 'C':	goto yy350;
	default:	goto yy336;
	}
yy347:
	yych = *++cur;
	switch (yych) {
	case '@':	goto yy351;
	default:	goto yy347;
	}
yy349:
	yych = *++cur;
	switch (yych) {
	case 'e':	goto yy353;
	default:	goto yy336;
	}
yy350:
	yych = *++cur;
	switch (yych) {
	case 'a':	goto yy354;
	default:	goto yy336;
	}
yy351:
	yych = *++cur;
	switch (yych) {
	case '\n':	goto yy336;
	case '\r':	goto yy355;
	default:	goto yy351;
	}
yy353:
	yych = *++cur;
	switch (yych) {
	case 'r':	goto yy357;
	default:	goto yy336;
	}
yy354:
	yych = *++cur;
	switch (yych) {
	case 'l':	goto yy358;
	default:	goto yy336;
	}
yy355:
	yych = *++cur;
	switch (yych) {
	case '\n':	goto yy359;
	case '\r':	goto yy355;
	default:	goto yy351;
	}
yy357:
	yych = *++cur;
	switch (yych) {
	case 's':	goto yy361;
	default:	goto yy336;
	}
yy358:
	yych = *++cur;
	switch (yych) {
	case 'l':	goto yy362;
	default:	goto yy336;
	}
yy359:
	++cur;
	tq1 = yyt1;
	tq2 = cur - 2;
#line 213 "src/lib/amipack_parse.re"
	{
              queue->members_size++;
              //queue->members = strndup(tq1, (int)(tq2 - tq1));
              //queue->members++;
              goto yyc_qmembers;
          }
#line 2554 "src/lib/amipack_parse.c"
yy361:
	yych = *++cur;
	switch (yych) {
	case ':':	goto yy363;
	default:	goto yy336;
	}
yy362:
	yych = *++cur;
	switch (yych) {
	case 'e':	goto yy364;
	default:	goto yy336;
	}
yy363:
	yych = *++cur;
	switch (yych) {
	case ' ':	goto yy365;
	default:	goto yy336;
	}
yy364:
	yych = *++cur;
	switch (yych) {
	case 'r':	goto yy366;
	default:	goto yy336;
	}
yy365:
	yych = *++cur;
	switch (yych) {
	case '\r':	goto yy367;
	default:	goto yy336;
	}
yy366:
	yych = *++cur;
	switch (yych) {
	case 's':	goto yy368;
	default:	goto yy336;
	}
yy367:
	yych = *++cur;
	switch (yych) {
	case '\n':	goto yy369;
	default:	goto yy336;
	}
yy368:
	yych = *++cur;
	switch (yych) {
	case '\r':	goto yy371;
	default:	goto yy336;
	}
yy369:
	++cur;
#line 223 "src/lib/amipack_parse.re"
	{
              queue->callers = calloc(QUEUE_LIST_LEN, QUEUE_ITEM_LEN);
              goto yyc_qcallers;
          }
#line 2610 "src/lib/amipack_parse.c"
yy371:
	yych = *++cur;
	switch (yych) {
	case '\n':	goto yy372;
	default:	goto yy336;
	}
yy372:
	yych = *++cur;
	switch (yych) {
	case '\r':	goto yy373;
	default:	goto yy336;
	}
yy373:
	yych = *++cur;
	switch (yych) {
	case '\n':	goto yy374;
	default:	goto yy336;
	}
yy374:
	++cur;
#line 219 "src/lib/amipack_parse.re"
	{
              queue->callers_size = 0;
              goto done;
          }
#line 2636 "src/lib/amipack_parse.c"
/* *********************************** */
yyc_qcallers:
	yych = *cur;
	switch (yych) {
	case '\r':	goto yy380;
	case ' ':	goto yy381;
	default:	goto yy378;
	}
yy378:
	++cur;
yy379:
#line 106 "src/lib/amipack_parse.re"
	{
              printf("====== UNKNOWN ERROR =====\n");
              if (hdr_name) free (hdr_name);
              amipack_destroy (pack);
              return NULL;
            }
#line 2655 "src/lib/amipack_parse.c"
yy380:
	yych = *++cur;
	switch (yych) {
	case '\n':	goto yy382;
	default:	goto yy379;
	}
yy381:
	yych = *(marker = ++cur);
	switch (yych) {
	case ' ':	goto yy384;
	default:	goto yy379;
	}
yy382:
	++cur;
#line 232 "src/lib/amipack_parse.re"
	{goto done;}
#line 2672 "src/lib/amipack_parse.c"
yy384:
	yych = *++cur;
	switch (yych) {
	case ' ':	goto yy386;
	default:	goto yy385;
	}
yy385:
	cur = marker;
	goto yy379;
yy386:
	yych = *++cur;
	switch (yych) {
	case ' ':	goto yy387;
	default:	goto yy385;
	}
yy387:
	yych = *++cur;
	switch (yych) {
	case ' ':	goto yy388;
	default:	goto yy385;
	}
yy388:
	yych = *++cur;
	switch (yych) {
	case ' ':	goto yy389;
	default:	goto yy385;
	}
yy389:
	yych = *++cur;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy390;
	default:	goto yy385;
	}
yy390:
	yych = *++cur;
	switch (yych) {
	case '.':	goto yy392;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy390;
	default:	goto yy385;
	}
yy392:
	yych = *++cur;
	switch (yych) {
	case ' ':	goto yy393;
	default:	goto yy385;
	}
yy393:
	yych = *++cur;
	switch (yych) {
	case '\n':	goto yy385;
	case '\r':	goto yy395;
	default:	goto yy393;
	}
yy395:
	yych = *++cur;
	switch (yych) {
	case '\n':	goto yy397;
	case '\r':	goto yy395;
	default:	goto yy393;
	}
yy397:
	++cur;
#line 228 "src/lib/amipack_parse.re"
	{
              queue->callers_size++;
              goto yyc_qcallers;
          }
#line 2758 "src/lib/amipack_parse.c"
}
#line 233 "src/lib/amipack_parse.re"


done:
  return pack;
}
