/* Generated by re2c 1.0.2 */
#line 1 "src/lib/amipack_parse.re"
/**
 * amiws -- Library with functions for read/create AMI packets
 * Copyright (C) 2016, Stas Kobzar <staskobzar@modulis.ca>
 *
 * This file is part of amiws.
 *
 * amiws is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * amiws is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with amiws.  If not, see <http://www.gnu.org/licenses/>.
 */

/**
 * @file amipack_parse.c
 * @brief AMI (Asterisk Management Interface) packet parser.
 *
 * @author Stas Kobzar <stas.kobzar@modulis.ca>
 */

#include <stdio.h>
#include <string.h>
#include "amipack.h"

/**
 * Commands to run when known header parsed.
 * @param name    Header type
 */
#define SET_HEADER(name)  len = cur - tok; \
                          hdr_name = strdup(name); \
                          goto yyc_key;

/**
 * Commands to run on Command AMI response header.
 * @param offset  Header name offset
 * @param name    Header type
 */
#define CMD_HEADER(offset, name) len = cur - tok - offset; tok += offset; \
                          while(*tok == ' ') { tok++; len--; } \
                          len -= 2; \
                          char *val = strndup(tok, len); \
                          amipack_append (pack, strdup(name), strlen(name), val, len); \
                          tok = cur; goto yyc_command;

// introducing types:re2c for AMI packet
/*! re2c parcing conditions. */
enum yycond_pack {
  yyckey,
  yycvalue,
  yyccommand,
  yycqueue,
};

AMIPacket *amiparse_pack (const char *pack_str)
{
  AMIPacket *pack = amipack_init ();
  AMIQueue  *queue = pack->queue;
  const char *marker = pack_str;
  const char *cur    = marker;
  const char *ctxmarker;
  int c = yyckey;
  int len = 0;

  const char *yyt1;
const char *yyt2;
const char *yyt3;


  const char *tok = marker;
  char *hdr_name;
  // stags
  const char *tq1, *tq2, *tq3, *tq4, *tq5, *tq6;


#line 85 "src/lib/amipack_parse.c"
{
	unsigned char yych;
	unsigned int yyaccept = 0;
	switch (c) {
	case yyckey: goto yyc_key;
	case yycqueue: goto yyc_queue;
	case yycvalue: goto yyc_value;
	case yyccommand: goto yyc_command;
	}
/* *********************************** */
yyc_key:
	yych = *cur;
	switch (yych) {
	case '\r':
		yyt1 = cur;
		goto yy6;
	case ' ':	goto yy7;
	case ':':
		yyt1 = cur;
		goto yy9;
	case 'A':
	case 'a':
		yyt1 = cur;
		goto yy11;
	case 'E':
	case 'e':
		yyt1 = cur;
		goto yy12;
	case 'R':
	case 'r':
		yyt1 = cur;
		goto yy13;
	default:
		yyt1 = cur;
		goto yy3;
	}
yy3:
	yyaccept = 0;
	yych = *(marker = ++cur);
yy4:
	switch (yych) {
	case ' ':	goto yy14;
	case ':':	goto yy16;
	default:	goto yy3;
	}
yy5:
#line 150 "src/lib/amipack_parse.re"
	{
              len = cur - tok;
              hdr_name = strndup(tok, len);
              goto yyc_key;
            }
#line 138 "src/lib/amipack_parse.c"
yy6:
	yyaccept = 0;
	yych = *(marker = ++cur);
	switch (yych) {
	case '\n':	goto yy18;
	default:	goto yy4;
	}
yy7:
	++cur;
#line 104 "src/lib/amipack_parse.re"
	{
              printf("====== UNKNOWN ERROR =====\n");
              if (hdr_name) free (hdr_name);
              amipack_destroy (pack);
              return NULL;
            }
#line 155 "src/lib/amipack_parse.c"
yy9:
	yyaccept = 1;
	yych = *(marker = ++cur);
	switch (yych) {
	case '\r':	goto yy19;
	case ' ':	goto yy20;
	default:	goto yy16;
	}
yy10:
#line 119 "src/lib/amipack_parse.re"
	{ tok = cur; goto yyc_value; }
#line 167 "src/lib/amipack_parse.c"
yy11:
	yyaccept = 0;
	yych = *(marker = ++cur);
	switch (yych) {
	case 'C':
	case 'c':	goto yy21;
	default:	goto yy4;
	}
yy12:
	yyaccept = 0;
	yych = *(marker = ++cur);
	switch (yych) {
	case 'V':
	case 'v':	goto yy22;
	default:	goto yy4;
	}
yy13:
	yyaccept = 0;
	yych = *(marker = ++cur);
	switch (yych) {
	case 'E':
	case 'e':	goto yy23;
	default:	goto yy4;
	}
yy14:
	yych = *++cur;
	switch (yych) {
	case 'h':	goto yy24;
	default:	goto yy15;
	}
yy15:
	cur = marker;
	switch (yyaccept) {
	case 0: 	goto yy5;
	case 1: 	goto yy10;
	case 2: 	goto yy35;
	case 3: 	goto yy38;
	case 4: 	goto yy45;
	case 5: 	goto yy50;
	case 6: 	goto yy55;
	case 7: 	goto yy62;
	default:	goto yy94;
	}
yy16:
	yych = *++cur;
yy17:
	switch (yych) {
	case ' ':	goto yy14;
	default:	goto yy16;
	}
yy18:
	yyaccept = 0;
	yych = *(marker = ++cur);
	switch (yych) {
	case '\r':	goto yy25;
	default:	goto yy4;
	}
yy19:
	yych = *++cur;
	switch (yych) {
	case '\n':	goto yy26;
	default:	goto yy17;
	}
yy20:
	yyaccept = 1;
	yych = *(marker = ++cur);
	switch (yych) {
	case 'h':	goto yy24;
	default:	goto yy29;
	}
yy21:
	yyaccept = 0;
	yych = *(marker = ++cur);
	switch (yych) {
	case 'T':
	case 't':	goto yy30;
	default:	goto yy4;
	}
yy22:
	yyaccept = 0;
	yych = *(marker = ++cur);
	switch (yych) {
	case 'E':
	case 'e':	goto yy31;
	default:	goto yy4;
	}
yy23:
	yyaccept = 0;
	yych = *(marker = ++cur);
	switch (yych) {
	case 'S':
	case 's':	goto yy32;
	default:	goto yy4;
	}
yy24:
	yych = *++cur;
	switch (yych) {
	case 'a':	goto yy33;
	default:	goto yy15;
	}
yy25:
	yyaccept = 0;
	yych = *(marker = ++cur);
	switch (yych) {
	case '\n':	goto yy34;
	default:	goto yy4;
	}
yy26:
	yych = *++cur;
	switch (yych) {
	case '\r':	goto yy36;
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy37;
	default:	goto yy17;
	}
yy27:
	yych = *++cur;
	switch (yych) {
	case '\n':	goto yy39;
	default:	goto yy15;
	}
yy28:
	yyaccept = 1;
	yych = *(marker = ++cur);
yy29:
	switch (yych) {
	case '\r':	goto yy27;
	case ' ':	goto yy28;
	default:	goto yy10;
	}
yy30:
	yyaccept = 0;
	yych = *(marker = ++cur);
	switch (yych) {
	case 'I':
	case 'i':	goto yy40;
	default:	goto yy4;
	}
yy31:
	yyaccept = 0;
	yych = *(marker = ++cur);
	switch (yych) {
	case 'N':
	case 'n':	goto yy41;
	default:	goto yy4;
	}
yy32:
	yyaccept = 0;
	yych = *(marker = ++cur);
	switch (yych) {
	case 'P':
	case 'p':	goto yy42;
	default:	goto yy4;
	}
yy33:
	yych = *++cur;
	switch (yych) {
	case 's':	goto yy43;
	default:	goto yy15;
	}
yy34:
	yyaccept = 2;
	yych = *(marker = ++cur);
	goto yy4;
yy35:
#line 110 "src/lib/amipack_parse.re"
	{ goto done; }
#line 385 "src/lib/amipack_parse.c"
yy36:
	yych = *++cur;
	switch (yych) {
	case '\n':	goto yy44;
	default:	goto yy17;
	}
yy37:
	yyaccept = 3;
	yych = *(marker = ++cur);
	goto yy17;
yy38:
	cur -= 1;
#line 120 "src/lib/amipack_parse.re"
	{
              tok = cur;
              amipack_append(pack, hdr_name, strlen(hdr_name), strdup(""), 0);
              goto yyc_key;
            }
#line 404 "src/lib/amipack_parse.c"
yy39:
	yych = *++cur;
	switch (yych) {
	case '\r':	goto yy46;
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy47;
	default:	goto yy15;
	}
yy40:
	yyaccept = 0;
	yych = *(marker = ++cur);
	switch (yych) {
	case 'O':
	case 'o':	goto yy48;
	default:	goto yy4;
	}
yy41:
	yyaccept = 0;
	yych = *(marker = ++cur);
	switch (yych) {
	case 'T':
	case 't':	goto yy49;
	default:	goto yy4;
	}
yy42:
	yyaccept = 0;
	yych = *(marker = ++cur);
	switch (yych) {
	case 'O':
	case 'o':	goto yy51;
	default:	goto yy4;
	}
yy43:
	yych = *++cur;
	switch (yych) {
	case ' ':	goto yy52;
	default:	goto yy15;
	}
yy44:
	yyaccept = 4;
	yych = *(marker = ++cur);
	goto yy17;
yy45:
#line 125 "src/lib/amipack_parse.re"
	{
              tok = cur;
              amipack_append(pack, hdr_name, strlen(hdr_name), strdup(""), 0);
              goto done;
            }
#line 504 "src/lib/amipack_parse.c"
yy46:
	yych = *++cur;
	switch (yych) {
	case '\n':	goto yy53;
	default:	goto yy15;
	}
yy47:
	++cur;
	goto yy38;
yy48:
	yyaccept = 0;
	yych = *(marker = ++cur);
	switch (yych) {
	case 'N':
	case 'n':	goto yy54;
	default:	goto yy4;
	}
yy49:
	yyaccept = 5;
	yych = *(marker = ++cur);
	goto yy4;
yy50:
#line 145 "src/lib/amipack_parse.re"
	{
              amipack_type (pack, AMI_EVENT);
              SET_HEADER("Event");
            }
#line 532 "src/lib/amipack_parse.c"
yy51:
	yyaccept = 0;
	yych = *(marker = ++cur);
	switch (yych) {
	case 'N':
	case 'n':	goto yy56;
	default:	goto yy4;
	}
yy52:
	yych = *++cur;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
		yyt2 = cur;
		goto yy57;
	default:	goto yy15;
	}
yy53:
	++cur;
	goto yy45;
yy54:
	yyaccept = 6;
	yych = *(marker = ++cur);
	goto yy4;
yy55:
#line 141 "src/lib/amipack_parse.re"
	{
              amipack_type (pack, AMI_ACTION);
              SET_HEADER("Action");
            }
#line 571 "src/lib/amipack_parse.c"
yy56:
	yyaccept = 0;
	yych = *(marker = ++cur);
	switch (yych) {
	case 'S':
	case 's':	goto yy59;
	default:	goto yy4;
	}
yy57:
	yych = *++cur;
	switch (yych) {
	case ' ':	goto yy60;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy57;
	default:	goto yy15;
	}
yy59:
	yyaccept = 0;
	yych = *(marker = ++cur);
	switch (yych) {
	case 'E':
	case 'e':	goto yy61;
	default:	goto yy4;
	}
yy60:
	yych = *++cur;
	switch (yych) {
	case 'c':	goto yy63;
	default:	goto yy15;
	}
yy61:
	yyaccept = 7;
	yych = *(marker = ++cur);
	switch (yych) {
	case ':':	goto yy64;
	default:	goto yy4;
	}
yy62:
#line 137 "src/lib/amipack_parse.re"
	{
              amipack_type (pack, AMI_RESPONSE);
              SET_HEADER("Response");
            }
#line 623 "src/lib/amipack_parse.c"
yy63:
	yych = *++cur;
	switch (yych) {
	case 'a':	goto yy65;
	default:	goto yy15;
	}
yy64:
	yych = *++cur;
	switch (yych) {
	case ' ':	goto yy66;
	case 'F':
	case 'f':	goto yy67;
	default:	goto yy16;
	}
yy65:
	yych = *++cur;
	switch (yych) {
	case 'l':	goto yy68;
	default:	goto yy15;
	}
yy66:
	yych = *++cur;
	switch (yych) {
	case 'h':	goto yy24;
	default:	goto yy70;
	}
yy67:
	yych = *++cur;
	switch (yych) {
	case 'O':
	case 'o':	goto yy72;
	default:	goto yy17;
	}
yy68:
	yych = *++cur;
	switch (yych) {
	case 'l':	goto yy73;
	default:	goto yy15;
	}
yy69:
	yych = *++cur;
yy70:
	switch (yych) {
	case ' ':	goto yy69;
	case 'F':
	case 'f':	goto yy71;
	default:	goto yy15;
	}
yy71:
	yych = *++cur;
	switch (yych) {
	case 'O':
	case 'o':	goto yy74;
	default:	goto yy15;
	}
yy72:
	yych = *++cur;
	switch (yych) {
	case 'L':
	case 'l':	goto yy75;
	default:	goto yy17;
	}
yy73:
	yych = *++cur;
	switch (yych) {
	case 's':	goto yy76;
	default:	goto yy15;
	}
yy74:
	yych = *++cur;
	switch (yych) {
	case 'L':
	case 'l':	goto yy77;
	default:	goto yy15;
	}
yy75:
	yych = *++cur;
	switch (yych) {
	case 'L':
	case 'l':	goto yy78;
	default:	goto yy17;
	}
yy76:
	yych = *++cur;
	switch (yych) {
	case ' ':	goto yy79;
	default:	goto yy15;
	}
yy77:
	yych = *++cur;
	switch (yych) {
	case 'L':
	case 'l':	goto yy80;
	default:	goto yy15;
	}
yy78:
	yych = *++cur;
	switch (yych) {
	case 'O':
	case 'o':	goto yy81;
	default:	goto yy17;
	}
yy79:
	yych = *++cur;
	switch (yych) {
	case '(':	goto yy82;
	default:	goto yy15;
	}
yy80:
	yych = *++cur;
	switch (yych) {
	case 'O':
	case 'o':	goto yy83;
	default:	goto yy15;
	}
yy81:
	yych = *++cur;
	switch (yych) {
	case 'W':
	case 'w':	goto yy84;
	default:	goto yy17;
	}
yy82:
	yych = *++cur;
	switch (yych) {
	case 'm':	goto yy85;
	default:	goto yy15;
	}
yy83:
	yych = *++cur;
	switch (yych) {
	case 'W':
	case 'w':	goto yy86;
	default:	goto yy15;
	}
yy84:
	yych = *++cur;
	switch (yych) {
	case 'S':
	case 's':	goto yy87;
	default:	goto yy17;
	}
yy85:
	yych = *++cur;
	switch (yych) {
	case 'a':	goto yy88;
	default:	goto yy15;
	}
yy86:
	yych = *++cur;
	switch (yych) {
	case 'S':
	case 's':	goto yy89;
	default:	goto yy15;
	}
yy87:
	yych = *++cur;
	switch (yych) {
	case '\r':	goto yy90;
	default:	goto yy17;
	}
yy88:
	yych = *++cur;
	switch (yych) {
	case 'x':	goto yy91;
	default:	goto yy15;
	}
yy89:
	yych = *++cur;
	switch (yych) {
	case '\r':	goto yy92;
	default:	goto yy15;
	}
yy90:
	yych = *++cur;
	switch (yych) {
	case '\n':	goto yy93;
	default:	goto yy17;
	}
yy91:
	yych = *++cur;
	switch (yych) {
	case ' ':	goto yy95;
	default:	goto yy15;
	}
yy92:
	yych = *++cur;
	switch (yych) {
	case '\n':	goto yy96;
	default:	goto yy15;
	}
yy93:
	yyaccept = 8;
	yych = *(marker = ++cur);
	goto yy17;
yy94:
#line 130 "src/lib/amipack_parse.re"
	{
              len = cur - tok;
              tok = cur;
              amipack_type (pack, AMI_RESPONSE);
              amipack_append(pack, strdup("Response"), 8, strdup("Follows"), 7);
              goto yyc_command;
            }
#line 828 "src/lib/amipack_parse.c"
yy95:
	yych = *++cur;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':
		yyt3 = cur;
		goto yy97;
	default:	goto yy15;
	}
yy96:
	++cur;
	goto yy94;
yy97:
	yych = *++cur;
	switch (yych) {
	case ')':	goto yy99;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy97;
	default:	goto yy15;
	}
yy99:
	yych = *++cur;
	switch (yych) {
	case ' ':	goto yy100;
	default:	goto yy15;
	}
yy100:
	++cur;
	tq1 = yyt1;
	tq3 = yyt2;
	tq5 = yyt3;
	tq2 = yyt2 - 5;
	tq4 = yyt3 - 12;
	tq6 = cur - 2;
#line 112 "src/lib/amipack_parse.re"
	{
              queue->name = strndup(tq1, (int)(tq2 - tq1));
              queue->calls = (int)strtol(tq3, NULL, 10);
              queue->maxlen = (int)strtol(tq5, NULL, 10);
              amipack_type (pack, AMI_QUEUES);
              goto yyc_queue;
            }
#line 939 "src/lib/amipack_parse.c"
/* *********************************** */
yyc_queue:
	yych = *cur;
	switch (yych) {
	case '\r':	goto yy106;
	case ' ':	goto yy107;
	case 'S':	goto yy108;
	case 'W':	goto yy109;
	case 'i':	goto yy110;
	default:	goto yy104;
	}
yy104:
	++cur;
yy105:
#line 104 "src/lib/amipack_parse.re"
	{
              printf("====== UNKNOWN ERROR =====\n");
              if (hdr_name) free (hdr_name);
              amipack_destroy (pack);
              return NULL;
            }
#line 961 "src/lib/amipack_parse.c"
yy106:
	yych = *(marker = ++cur);
	switch (yych) {
	case '\n':	goto yy111;
	default:	goto yy105;
	}
yy107:
	yych = *(marker = ++cur);
	switch (yych) {
	case ' ':	goto yy113;
	default:	goto yy105;
	}
yy108:
	yych = *(marker = ++cur);
	switch (yych) {
	case 'L':	goto yy114;
	default:	goto yy105;
	}
yy109:
	yych = *(marker = ++cur);
	switch (yych) {
	case ':':	goto yy115;
	default:	goto yy105;
	}
yy110:
	yych = *(marker = ++cur);
	switch (yych) {
	case 'n':	goto yy116;
	default:	goto yy105;
	}
yy111:
	yych = *++cur;
	switch (yych) {
	case '\r':	goto yy117;
	default:	goto yy112;
	}
yy112:
	cur = marker;
	goto yy105;
yy113:
	yych = *++cur;
	switch (yych) {
	case ' ':	goto yy118;
	default:	goto yy112;
	}
yy114:
	yych = *++cur;
	switch (yych) {
	case ':':	goto yy119;
	default:	goto yy112;
	}
yy115:
	yych = *++cur;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
		yyt1 = cur;
		goto yy120;
	default:	goto yy112;
	}
yy116:
	yych = *++cur;
	switch (yych) {
	case ' ':	goto yy122;
	default:	goto yy112;
	}
yy117:
	yych = *++cur;
	switch (yych) {
	case '\n':	goto yy123;
	default:	goto yy112;
	}
yy118:
	yych = *++cur;
	switch (yych) {
	case ' ':	goto yy125;
	case 'C':	goto yy126;
	case 'M':	goto yy127;
	case 'N':	goto yy128;
	default:	goto yy112;
	}
yy119:
	yych = *++cur;
	switch (yych) {
	case '.':
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
		yyt1 = cur;
		goto yy129;
	default:	goto yy112;
	}
yy120:
	yych = *++cur;
	switch (yych) {
	case ',':	goto yy131;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy120;
	default:	goto yy112;
	}
yy122:
	yych = *++cur;
	switch (yych) {
	case '\'':	goto yy132;
	default:	goto yy112;
	}
yy123:
	++cur;
#line 110 "src/lib/amipack_parse.re"
	{ goto done; }
#line 1095 "src/lib/amipack_parse.c"
yy125:
	yych = *++cur;
	switch (yych) {
	case ' ':	goto yy133;
	default:	goto yy112;
	}
yy126:
	yych = *++cur;
	switch (yych) {
	case 'a':	goto yy134;
	default:	goto yy112;
	}
yy127:
	yych = *++cur;
	switch (yych) {
	case 'e':	goto yy135;
	default:	goto yy112;
	}
yy128:
	yych = *++cur;
	switch (yych) {
	case 'o':	goto yy136;
	default:	goto yy112;
	}
yy129:
	yych = *++cur;
	switch (yych) {
	case '%':	goto yy137;
	case '.':
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy129;
	default:	goto yy112;
	}
yy131:
	yych = *++cur;
	switch (yych) {
	case ' ':	goto yy138;
	default:	goto yy112;
	}
yy132:
	yych = *++cur;
	switch (yych) {
	case '\'':	goto yy112;
	default:
		yyt1 = cur;
		goto yy139;
	}
yy133:
	yych = *++cur;
	switch (yych) {
	case ' ':	goto yy141;
	default:	goto yy112;
	}
yy134:
	yych = *++cur;
	switch (yych) {
	case 'l':	goto yy142;
	default:	goto yy112;
	}
yy135:
	yych = *++cur;
	switch (yych) {
	case 'm':	goto yy143;
	default:	goto yy112;
	}
yy136:
	yych = *++cur;
	switch (yych) {
	case ' ':	goto yy144;
	default:	goto yy112;
	}
yy137:
	yych = *++cur;
	switch (yych) {
	case ' ':	goto yy145;
	default:	goto yy112;
	}
yy138:
	yych = *++cur;
	switch (yych) {
	case 'C':	goto yy146;
	default:	goto yy112;
	}
yy139:
	yych = *++cur;
	switch (yych) {
	case '\'':	goto yy147;
	default:	goto yy139;
	}
yy141:
	yych = *++cur;
	switch (yych) {
	case '0':
	case '1':	goto yy148;
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy150;
	default:	goto yy112;
	}
yy142:
	yych = *++cur;
	switch (yych) {
	case 'l':	goto yy151;
	default:	goto yy112;
	}
yy143:
	yych = *++cur;
	switch (yych) {
	case 'b':	goto yy152;
	default:	goto yy112;
	}
yy144:
	yych = *++cur;
	switch (yych) {
	case 'C':	goto yy153;
	case 'M':	goto yy154;
	default:	goto yy112;
	}
yy145:
	yych = *++cur;
	switch (yych) {
	case 'w':	goto yy155;
	default:	goto yy112;
	}
yy146:
	yych = *++cur;
	switch (yych) {
	case ':':	goto yy156;
	default:	goto yy112;
	}
yy147:
	yych = *++cur;
	switch (yych) {
	case ' ':	goto yy157;
	default:	goto yy112;
	}
yy148:
	yych = *++cur;
	switch (yych) {
	case '.':	goto yy158;
	case '0':
	case '1':	goto yy148;
	default:	goto yy112;
	}
yy150:
	yych = *++cur;
	switch (yych) {
	case '@':	goto yy112;
	default:	goto yy159;
	}
yy151:
	yych = *++cur;
	switch (yych) {
	case 'e':	goto yy161;
	default:	goto yy112;
	}
yy152:
	yych = *++cur;
	switch (yych) {
	case 'e':	goto yy162;
	default:	goto yy112;
	}
yy153:
	yych = *++cur;
	switch (yych) {
	case 'a':	goto yy163;
	default:	goto yy112;
	}
yy154:
	yych = *++cur;
	switch (yych) {
	case 'e':	goto yy164;
	default:	goto yy112;
	}
yy155:
	yych = *++cur;
	switch (yych) {
	case 'i':	goto yy165;
	default:	goto yy112;
	}
yy156:
	yych = *++cur;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
		yyt2 = cur;
		goto yy166;
	default:	goto yy112;
	}
yy157:
	yych = *++cur;
	switch (yych) {
	case 's':	goto yy168;
	default:	goto yy112;
	}
yy158:
	yych = *++cur;
	switch (yych) {
	case ' ':	goto yy169;
	default:	goto yy112;
	}
yy159:
	yych = *++cur;
	switch (yych) {
	case '@':	goto yy170;
	default:	goto yy159;
	}
yy161:
	yych = *++cur;
	switch (yych) {
	case 'r':	goto yy171;
	default:	goto yy112;
	}
yy162:
	yych = *++cur;
	switch (yych) {
	case 'r':	goto yy172;
	default:	goto yy112;
	}
yy163:
	yych = *++cur;
	switch (yych) {
	case 'l':	goto yy173;
	default:	goto yy112;
	}
yy164:
	yych = *++cur;
	switch (yych) {
	case 'm':	goto yy174;
	default:	goto yy112;
	}
yy165:
	yych = *++cur;
	switch (yych) {
	case 't':	goto yy175;
	default:	goto yy112;
	}
yy166:
	yych = *++cur;
	switch (yych) {
	case ',':	goto yy176;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy166;
	default:	goto yy112;
	}
yy168:
	yych = *++cur;
	switch (yych) {
	case 't':	goto yy177;
	default:	goto yy112;
	}
yy169:
	yych = *++cur;
	switch (yych) {
	case ' ':	goto yy112;
	default:	goto yy178;
	}
yy170:
	yych = *++cur;
	switch (yych) {
	case ' ':	goto yy112;
	default:	goto yy180;
	}
yy171:
	yych = *++cur;
	switch (yych) {
	case ':':	goto yy181;
	default:	goto yy112;
	}
yy172:
	yych = *++cur;
	switch (yych) {
	case 's':	goto yy182;
	default:	goto yy112;
	}
yy173:
	yych = *++cur;
	switch (yych) {
	case 'l':	goto yy183;
	default:	goto yy112;
	}
yy174:
	yych = *++cur;
	switch (yych) {
	case 'b':	goto yy184;
	default:	goto yy112;
	}
yy175:
	yych = *++cur;
	switch (yych) {
	case 'h':	goto yy185;
	default:	goto yy112;
	}
yy176:
	yych = *++cur;
	switch (yych) {
	case ' ':	goto yy186;
	default:	goto yy112;
	}
yy177:
	yych = *++cur;
	switch (yych) {
	case 'r':	goto yy187;
	default:	goto yy112;
	}
yy178:
	yych = *++cur;
	switch (yych) {
	case ' ':	goto yy112;
	case '(':	goto yy188;
	default:	goto yy178;
	}
yy180:
	yych = *++cur;
	switch (yych) {
	case ' ':	goto yy190;
	default:	goto yy112;
	}
yy181:
	yych = *++cur;
	switch (yych) {
	case ' ':	goto yy192;
	default:	goto yy112;
	}
yy182:
	yych = *++cur;
	switch (yych) {
	case ':':	goto yy193;
	default:	goto yy112;
	}
yy183:
	yych = *++cur;
	switch (yych) {
	case 'e':	goto yy194;
	default:	goto yy112;
	}
yy184:
	yych = *++cur;
	switch (yych) {
	case 'e':	goto yy195;
	default:	goto yy112;
	}
yy185:
	yych = *++cur;
	switch (yych) {
	case 'i':	goto yy196;
	default:	goto yy112;
	}
yy186:
	yych = *++cur;
	switch (yych) {
	case 'A':	goto yy197;
	default:	goto yy112;
	}
yy187:
	yych = *++cur;
	switch (yych) {
	case 'a':	goto yy198;
	default:	goto yy112;
	}
yy188:
	yych = *++cur;
	switch (yych) {
	case ' ':	goto yy112;
	case '(':	goto yy188;
	case 'w':	goto yy199;
	default:	goto yy178;
	}
yy190:
	yych = *++cur;
	switch (yych) {
	case '\n':	goto yy112;
	case '\r':	goto yy200;
	default:	goto yy190;
	}
yy192:
	yych = *++cur;
	switch (yych) {
	case '\r':	goto yy202;
	default:	goto yy112;
	}
yy193:
	yych = *++cur;
	switch (yych) {
	case ' ':	goto yy203;
	default:	goto yy112;
	}
yy194:
	yych = *++cur;
	switch (yych) {
	case 'r':	goto yy204;
	default:	goto yy112;
	}
yy195:
	yych = *++cur;
	switch (yych) {
	case 'r':	goto yy205;
	default:	goto yy112;
	}
yy196:
	yych = *++cur;
	switch (yych) {
	case 'n':	goto yy206;
	default:	goto yy112;
	}
yy197:
	yych = *++cur;
	switch (yych) {
	case ':':	goto yy207;
	default:	goto yy112;
	}
yy198:
	yych = *++cur;
	switch (yych) {
	case 't':	goto yy208;
	default:	goto yy112;
	}
yy199:
	yych = *++cur;
	switch (yych) {
	case ' ':	goto yy112;
	case '(':	goto yy188;
	case 'a':	goto yy209;
	default:	goto yy178;
	}
yy200:
	yych = *++cur;
	switch (yych) {
	case '\n':	goto yy210;
	case '\r':	goto yy200;
	default:	goto yy190;
	}
yy202:
	yych = *++cur;
	switch (yych) {
	case '\n':	goto yy212;
	default:	goto yy112;
	}
yy203:
	yych = *++cur;
	switch (yych) {
	case '\r':	goto yy214;
	default:	goto yy112;
	}
yy204:
	yych = *++cur;
	switch (yych) {
	case 's':	goto yy215;
	default:	goto yy112;
	}
yy205:
	yych = *++cur;
	switch (yych) {
	case 's':	goto yy216;
	default:	goto yy112;
	}
yy206:
	yych = *++cur;
	switch (yych) {
	case ' ':	goto yy217;
	default:	goto yy112;
	}
yy207:
	yych = *++cur;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
		yyt3 = cur;
		goto yy218;
	default:	goto yy112;
	}
yy208:
	yych = *++cur;
	switch (yych) {
	case 'e':	goto yy220;
	default:	goto yy112;
	}
yy209:
	yych = *++cur;
	switch (yych) {
	case ' ':	goto yy112;
	case '(':	goto yy188;
	case 'i':	goto yy221;
	default:	goto yy178;
	}
yy210:
	++cur;
#line 203 "src/lib/amipack_parse.re"
	{queue->members_size++; goto yyc_queue;}
#line 1666 "src/lib/amipack_parse.c"
yy212:
	++cur;
#line 204 "src/lib/amipack_parse.re"
	{goto yyc_queue;}
#line 1671 "src/lib/amipack_parse.c"
yy214:
	yych = *++cur;
	switch (yych) {
	case '\n':	goto yy222;
	default:	goto yy112;
	}
yy215:
	yych = *++cur;
	switch (yych) {
	case '\r':	goto yy224;
	default:	goto yy112;
	}
yy216:
	yych = *++cur;
	switch (yych) {
	case '\r':	goto yy225;
	default:	goto yy112;
	}
yy217:
	yych = *++cur;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
		yyt2 = cur;
		goto yy226;
	default:	goto yy112;
	}
yy218:
	yych = *++cur;
	switch (yych) {
	case ',':	goto yy228;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy218;
	default:	goto yy112;
	}
yy220:
	yych = *++cur;
	switch (yych) {
	case 'g':	goto yy229;
	default:	goto yy112;
	}
yy221:
	yych = *++cur;
	switch (yych) {
	case ' ':	goto yy112;
	case '(':	goto yy188;
	case 't':	goto yy230;
	default:	goto yy178;
	}
yy222:
	++cur;
#line 202 "src/lib/amipack_parse.re"
	{goto yyc_queue;}
#line 1741 "src/lib/amipack_parse.c"
yy224:
	yych = *++cur;
	switch (yych) {
	case '\n':	goto yy231;
	default:	goto yy112;
	}
yy225:
	yych = *++cur;
	switch (yych) {
	case '\n':	goto yy232;
	default:	goto yy112;
	}
yy226:
	yych = *++cur;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy226;
	case 's':	goto yy234;
	default:	goto yy112;
	}
yy228:
	yych = *++cur;
	switch (yych) {
	case ' ':	goto yy235;
	default:	goto yy112;
	}
yy229:
	yych = *++cur;
	switch (yych) {
	case 'y':	goto yy237;
	default:	goto yy112;
	}
yy230:
	yych = *++cur;
	switch (yych) {
	case ' ':	goto yy112;
	case '(':	goto yy188;
	case ':':	goto yy238;
	default:	goto yy178;
	}
yy231:
	yych = *++cur;
	switch (yych) {
	case '\r':	goto yy239;
	default:	goto yy112;
	}
yy232:
	++cur;
#line 192 "src/lib/amipack_parse.re"
	{
              printf("==NO MEMBERS==\n");
              pack->queue->members_size = 0;
              goto yyc_queue;
          }
#line 1804 "src/lib/amipack_parse.c"
yy234:
	yych = *++cur;
	switch (yych) {
	case '\r':	goto yy240;
	default:	goto yy112;
	}
yy235:
	++cur;
	tq1 = yyt1;
	tq3 = yyt2;
	tq5 = yyt3;
	tq2 = yyt2 - 4;
	tq4 = yyt3 - 4;
	tq6 = cur - 2;
#line 181 "src/lib/amipack_parse.re"
	{
              queue->weight = (int)strtol(tq1, NULL, 10);
              queue->callscompleted = (int)strtol(tq3, NULL, 10);
              queue->callsabandoned = (int)strtol(tq5, NULL, 10);
              goto yyc_queue;
          }
#line 1826 "src/lib/amipack_parse.c"
yy237:
	yych = *++cur;
	switch (yych) {
	case ' ':	goto yy241;
	default:	goto yy112;
	}
yy238:
	yych = *++cur;
	switch (yych) {
	case ' ':	goto yy242;
	case '(':	goto yy188;
	default:	goto yy178;
	}
yy239:
	yych = *++cur;
	switch (yych) {
	case '\n':	goto yy243;
	default:	goto yy112;
	}
yy240:
	yych = *++cur;
	switch (yych) {
	case '\n':	goto yy245;
	default:	goto yy112;
	}
yy241:
	yych = *++cur;
	switch (yych) {
	case '(':	goto yy247;
	default:	goto yy112;
	}
yy242:
	yych = *++cur;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy248;
	default:	goto yy112;
	}
yy243:
	++cur;
#line 197 "src/lib/amipack_parse.re"
	{
              pack->queue->callers_size = 0;
              printf("==NO CALLERS==\n");
              goto done;
          }
#line 1881 "src/lib/amipack_parse.c"
yy245:
	++cur;
	tq1 = yyt1;
	tq3 = yyt2;
	tq2 = yyt2 - 9;
	tq4 = cur - 3;
#line 187 "src/lib/amipack_parse.re"
	{
              queue->sl = strndup(tq1, (int)(tq2 - tq1));
              queue->sl_sec = (int)strtol(tq3, NULL, 10);
              goto yyc_queue;
          }
#line 1894 "src/lib/amipack_parse.c"
yy247:
	yych = *++cur;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
		yyt2 = cur;
		goto yy250;
	default:	goto yy112;
	}
yy248:
	yych = *++cur;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy248;
	case ':':	goto yy252;
	default:	goto yy112;
	}
yy250:
	yych = *++cur;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy250;
	case 's':	goto yy253;
	default:	goto yy112;
	}
yy252:
	yych = *++cur;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy254;
	default:	goto yy112;
	}
yy253:
	yych = *++cur;
	switch (yych) {
	case ' ':	goto yy256;
	default:	goto yy112;
	}
yy254:
	yych = *++cur;
	switch (yych) {
	case ',':	goto yy257;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy254;
	default:	goto yy112;
	}
yy256:
	yych = *++cur;
	switch (yych) {
	case 'h':	goto yy258;
	default:	goto yy112;
	}
yy257:
	yych = *++cur;
	switch (yych) {
	case ' ':	goto yy259;
	default:	goto yy112;
	}
yy258:
	yych = *++cur;
	switch (yych) {
	case 'o':	goto yy260;
	default:	goto yy112;
	}
yy259:
	yych = *++cur;
	switch (yych) {
	case 'p':	goto yy261;
	default:	goto yy112;
	}
yy260:
	yych = *++cur;
	switch (yych) {
	case 'l':	goto yy262;
	default:	goto yy112;
	}
yy261:
	yych = *++cur;
	switch (yych) {
	case 'r':	goto yy263;
	default:	goto yy112;
	}
yy262:
	yych = *++cur;
	switch (yych) {
	case 'd':	goto yy264;
	default:	goto yy112;
	}
yy263:
	yych = *++cur;
	switch (yych) {
	case 'i':	goto yy265;
	default:	goto yy112;
	}
yy264:
	yych = *++cur;
	switch (yych) {
	case 't':	goto yy266;
	default:	goto yy112;
	}
yy265:
	yych = *++cur;
	switch (yych) {
	case 'o':	goto yy267;
	default:	goto yy112;
	}
yy266:
	yych = *++cur;
	switch (yych) {
	case 'i':	goto yy268;
	default:	goto yy112;
	}
yy267:
	yych = *++cur;
	switch (yych) {
	case ':':	goto yy269;
	default:	goto yy112;
	}
yy268:
	yych = *++cur;
	switch (yych) {
	case 'm':	goto yy270;
	default:	goto yy112;
	}
yy269:
	yych = *++cur;
	switch (yych) {
	case ' ':	goto yy271;
	default:	goto yy112;
	}
yy270:
	yych = *++cur;
	switch (yych) {
	case 'e':	goto yy272;
	default:	goto yy112;
	}
yy271:
	yych = *++cur;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy273;
	default:	goto yy112;
	}
yy272:
	yych = *++cur;
	switch (yych) {
	case ',':	goto yy275;
	default:	goto yy112;
	}
yy273:
	yych = *++cur;
	switch (yych) {
	case ')':	goto yy276;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy273;
	default:	goto yy112;
	}
yy275:
	yych = *++cur;
	switch (yych) {
	case ' ':	goto yy277;
	default:	goto yy112;
	}
yy276:
	yych = *++cur;
	switch (yych) {
	case '\r':	goto yy278;
	default:	goto yy112;
	}
yy277:
	yych = *++cur;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
		yyt3 = cur;
		goto yy279;
	default:	goto yy112;
	}
yy278:
	yych = *++cur;
	switch (yych) {
	case '\n':	goto yy281;
	default:	goto yy112;
	}
yy279:
	yych = *++cur;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy279;
	case 's':	goto yy283;
	default:	goto yy112;
	}
yy281:
	++cur;
#line 205 "src/lib/amipack_parse.re"
	{queue->members_size++; goto yyc_queue;}
#line 2163 "src/lib/amipack_parse.c"
yy283:
	yych = *++cur;
	switch (yych) {
	case ' ':	goto yy284;
	default:	goto yy112;
	}
yy284:
	yych = *++cur;
	switch (yych) {
	case 't':	goto yy285;
	default:	goto yy112;
	}
yy285:
	yych = *++cur;
	switch (yych) {
	case 'a':	goto yy286;
	default:	goto yy112;
	}
yy286:
	yych = *++cur;
	switch (yych) {
	case 'l':	goto yy287;
	default:	goto yy112;
	}
yy287:
	yych = *++cur;
	switch (yych) {
	case 'k':	goto yy288;
	default:	goto yy112;
	}
yy288:
	yych = *++cur;
	switch (yych) {
	case 't':	goto yy289;
	default:	goto yy112;
	}
yy289:
	yych = *++cur;
	switch (yych) {
	case 'i':	goto yy290;
	default:	goto yy112;
	}
yy290:
	yych = *++cur;
	switch (yych) {
	case 'm':	goto yy291;
	default:	goto yy112;
	}
yy291:
	yych = *++cur;
	switch (yych) {
	case 'e':	goto yy292;
	default:	goto yy112;
	}
yy292:
	yych = *++cur;
	switch (yych) {
	case ')':	goto yy293;
	default:	goto yy112;
	}
yy293:
	yych = *++cur;
	switch (yych) {
	case ',':	goto yy294;
	default:	goto yy112;
	}
yy294:
	yych = *++cur;
	switch (yych) {
	case ' ':	goto yy295;
	default:	goto yy112;
	}
yy295:
	++cur;
	tq1 = yyt1;
	tq3 = yyt2;
	tq5 = yyt3;
	tq2 = yyt2 - 12;
	tq4 = yyt3 - 12;
	tq6 = cur - 13;
#line 175 "src/lib/amipack_parse.re"
	{
              queue->strategy = strndup(tq1, (int)(tq2 - tq1));
              queue->holdtime = (int)strtol(tq3, NULL, 10);
              queue->talktime = (int)strtol(tq5, NULL, 10);
              goto yyc_queue;
          }
#line 2251 "src/lib/amipack_parse.c"
/* *********************************** */
yyc_value:
	yych = *cur;
	switch (yych) {
	case '\n':	goto yy302;
	case '\r':	goto yy304;
	default:	goto yy299;
	}
yy299:
	yych = *++cur;
	switch (yych) {
	case '\n':
	case '\r':	goto yy301;
	default:	goto yy299;
	}
yy301:
#line 157 "src/lib/amipack_parse.re"
	{
              len = cur - tok;
              char *val = strndup(tok, len);
              amipack_append(pack, hdr_name, strlen(hdr_name), val, len);
              goto yyc_value;
            }
#line 2275 "src/lib/amipack_parse.c"
yy302:
	++cur;
yy303:
#line 104 "src/lib/amipack_parse.re"
	{
              printf("====== UNKNOWN ERROR =====\n");
              if (hdr_name) free (hdr_name);
              amipack_destroy (pack);
              return NULL;
            }
#line 2286 "src/lib/amipack_parse.c"
yy304:
	yych = *(marker = ++cur);
	switch (yych) {
	case '\n':	goto yy305;
	default:	goto yy303;
	}
yy305:
	yych = *++cur;
	switch (yych) {
	case '\r':	goto yy307;
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy308;
	default:	goto yy306;
	}
yy306:
	cur = marker;
	goto yy303;
yy307:
	yych = *++cur;
	switch (yych) {
	case '\n':	goto yy310;
	default:	goto yy306;
	}
yy308:
	++cur;
	cur -= 1;
#line 156 "src/lib/amipack_parse.re"
	{ tok = cur; goto yyc_key; }
#line 2365 "src/lib/amipack_parse.c"
yy310:
	++cur;
#line 110 "src/lib/amipack_parse.re"
	{ goto done; }
#line 2370 "src/lib/amipack_parse.c"
/* *********************************** */
yyc_command:
	yych = *cur;
	switch (yych) {
	case '\n':	goto yy316;
	case '-':	goto yy318;
	case 'A':
	case 'a':	goto yy319;
	case 'M':
	case 'm':	goto yy320;
	case 'P':
	case 'p':	goto yy321;
	default:	goto yy314;
	}
yy314:
	yych = *++cur;
yy315:
	switch (yych) {
	case '\n':	goto yy316;
	default:	goto yy314;
	}
yy316:
	++cur;
yy317:
#line 168 "src/lib/amipack_parse.re"
	{ goto yyc_command; }
#line 2397 "src/lib/amipack_parse.c"
yy318:
	yych = *++cur;
	switch (yych) {
	case '-':	goto yy322;
	default:	goto yy315;
	}
yy319:
	yych = *++cur;
	switch (yych) {
	case 'C':
	case 'c':	goto yy323;
	default:	goto yy315;
	}
yy320:
	yych = *++cur;
	switch (yych) {
	case 'E':
	case 'e':	goto yy324;
	default:	goto yy315;
	}
yy321:
	yych = *++cur;
	switch (yych) {
	case 'R':
	case 'r':	goto yy325;
	default:	goto yy315;
	}
yy322:
	yych = *++cur;
	switch (yych) {
	case 'E':	goto yy326;
	default:	goto yy315;
	}
yy323:
	yych = *++cur;
	switch (yych) {
	case 'T':
	case 't':	goto yy327;
	default:	goto yy315;
	}
yy324:
	yych = *++cur;
	switch (yych) {
	case 'S':
	case 's':	goto yy328;
	default:	goto yy315;
	}
yy325:
	yych = *++cur;
	switch (yych) {
	case 'I':
	case 'i':	goto yy329;
	default:	goto yy315;
	}
yy326:
	yych = *++cur;
	switch (yych) {
	case 'N':	goto yy330;
	default:	goto yy315;
	}
yy327:
	yych = *++cur;
	switch (yych) {
	case 'I':
	case 'i':	goto yy331;
	default:	goto yy315;
	}
yy328:
	yych = *++cur;
	switch (yych) {
	case 'S':
	case 's':	goto yy332;
	default:	goto yy315;
	}
yy329:
	yych = *++cur;
	switch (yych) {
	case 'V':
	case 'v':	goto yy333;
	default:	goto yy315;
	}
yy330:
	yych = *++cur;
	switch (yych) {
	case 'D':	goto yy334;
	default:	goto yy315;
	}
yy331:
	yych = *++cur;
	switch (yych) {
	case 'O':
	case 'o':	goto yy335;
	default:	goto yy315;
	}
yy332:
	yych = *++cur;
	switch (yych) {
	case 'A':
	case 'a':	goto yy336;
	default:	goto yy315;
	}
yy333:
	yych = *++cur;
	switch (yych) {
	case 'I':
	case 'i':	goto yy337;
	default:	goto yy315;
	}
yy334:
	yych = *++cur;
	switch (yych) {
	case ' ':	goto yy338;
	default:	goto yy315;
	}
yy335:
	yych = *++cur;
	switch (yych) {
	case 'N':
	case 'n':	goto yy339;
	default:	goto yy315;
	}
yy336:
	yych = *++cur;
	switch (yych) {
	case 'G':
	case 'g':	goto yy340;
	default:	goto yy315;
	}
yy337:
	yych = *++cur;
	switch (yych) {
	case 'L':
	case 'l':	goto yy341;
	default:	goto yy315;
	}
yy338:
	yych = *++cur;
	switch (yych) {
	case 'C':	goto yy342;
	default:	goto yy315;
	}
yy339:
	yych = *++cur;
	switch (yych) {
	case 'I':
	case 'i':	goto yy343;
	default:	goto yy315;
	}
yy340:
	yych = *++cur;
	switch (yych) {
	case 'E':
	case 'e':	goto yy344;
	default:	goto yy315;
	}
yy341:
	yych = *++cur;
	switch (yych) {
	case 'E':
	case 'e':	goto yy345;
	default:	goto yy315;
	}
yy342:
	yych = *++cur;
	switch (yych) {
	case 'O':	goto yy346;
	default:	goto yy315;
	}
yy343:
	yych = *++cur;
	switch (yych) {
	case 'D':
	case 'd':	goto yy347;
	default:	goto yy315;
	}
yy344:
	yych = *++cur;
	switch (yych) {
	case ':':	goto yy348;
	default:	goto yy315;
	}
yy345:
	yych = *++cur;
	switch (yych) {
	case 'G':
	case 'g':	goto yy350;
	default:	goto yy315;
	}
yy346:
	yych = *++cur;
	switch (yych) {
	case 'M':	goto yy351;
	default:	goto yy315;
	}
yy347:
	yych = *++cur;
	switch (yych) {
	case ':':	goto yy352;
	default:	goto yy315;
	}
yy348:
	yych = *++cur;
	switch (yych) {
	case '\n':	goto yy316;
	case '\r':	goto yy354;
	default:	goto yy348;
	}
yy350:
	yych = *++cur;
	switch (yych) {
	case 'E':
	case 'e':	goto yy356;
	default:	goto yy315;
	}
yy351:
	yych = *++cur;
	switch (yych) {
	case 'M':	goto yy357;
	default:	goto yy315;
	}
yy352:
	yych = *++cur;
	switch (yych) {
	case '\n':	goto yy316;
	case '\r':	goto yy358;
	default:	goto yy352;
	}
yy354:
	yych = *++cur;
	switch (yych) {
	case '\n':	goto yy360;
	case '\r':	goto yy354;
	default:	goto yy348;
	}
yy356:
	yych = *++cur;
	switch (yych) {
	case ':':	goto yy362;
	default:	goto yy315;
	}
yy357:
	yych = *++cur;
	switch (yych) {
	case 'A':	goto yy364;
	default:	goto yy315;
	}
yy358:
	yych = *++cur;
	switch (yych) {
	case '\n':	goto yy365;
	case '\r':	goto yy358;
	default:	goto yy352;
	}
yy360:
	++cur;
#line 166 "src/lib/amipack_parse.re"
	{ CMD_HEADER(8, "Message"); }
#line 2655 "src/lib/amipack_parse.c"
yy362:
	yych = *++cur;
	switch (yych) {
	case '\n':	goto yy316;
	case '\r':	goto yy367;
	default:	goto yy362;
	}
yy364:
	yych = *++cur;
	switch (yych) {
	case 'N':	goto yy369;
	default:	goto yy315;
	}
yy365:
	++cur;
#line 165 "src/lib/amipack_parse.re"
	{ CMD_HEADER(9, "ActionID"); }
#line 2673 "src/lib/amipack_parse.c"
yy367:
	yych = *++cur;
	switch (yych) {
	case '\n':	goto yy370;
	case '\r':	goto yy367;
	default:	goto yy362;
	}
yy369:
	yych = *++cur;
	switch (yych) {
	case 'D':	goto yy372;
	default:	goto yy315;
	}
yy370:
	++cur;
#line 164 "src/lib/amipack_parse.re"
	{ CMD_HEADER(10, "Privilege"); }
#line 2691 "src/lib/amipack_parse.c"
yy372:
	yych = *++cur;
	switch (yych) {
	case '-':	goto yy373;
	default:	goto yy315;
	}
yy373:
	yych = *++cur;
	switch (yych) {
	case '-':	goto yy374;
	default:	goto yy315;
	}
yy374:
	yych = *++cur;
	switch (yych) {
	case '\r':	goto yy375;
	default:	goto yy315;
	}
yy375:
	yych = *++cur;
	switch (yych) {
	case '\n':	goto yy376;
	default:	goto yy314;
	}
yy376:
	yych = *(marker = ++cur);
	switch (yych) {
	case '\r':	goto yy377;
	default:	goto yy317;
	}
yy377:
	yych = *++cur;
	switch (yych) {
	case '\n':	goto yy379;
	default:	goto yy378;
	}
yy378:
	cur = marker;
	goto yy317;
yy379:
	++cur;
#line 169 "src/lib/amipack_parse.re"
	{
              len = cur - tok - 19; // output minus command end tag
              char *val = strndup(tok, len);
              amipack_append (pack, strdup("Output"), 6, val, len);
              goto done;
            }
#line 2740 "src/lib/amipack_parse.c"
}
#line 206 "src/lib/amipack_parse.re"


done:
  return pack;
}
